### ISSUE TITLE
Tarea 1 - Problemas con la visualización

### ISSUE THREAD

**Issue by pstassara** [IIC2133-PUC/2020-2#101]
Hola! Estoy trabajando en Mac y cuando corro mi programa con la visualización (sin el flag --novis), esta aparece en pantalla y funciona por unos segundos, pero después se queda pegada. El programa se sigue ejecutando y la ventana se cierra cuando termina. Hay veces que demora más en quedar pegada y otras menos. El output del programa es el correcto, lo probé con todos los tests. Tampoco tengo errores de memoria.

Cuando lo corro en la máquina virtual (en la que uso valgrind) con el flag --novis, no tengo problema, pero cuando lo hago sin el flag me arroja `sh: 1: ./visualizer_core: Exec format error` , no aparece la visualización y el programa se cae. 

Instalé todas las librerías, tanto en Mac como en la máquina virtual, según la guía de instalación que entregaron.

Qué podrá ser?

**Comment by vichoeq** [comment]
Hola, la visualización a veces se queda pegada, es por un tema de compatibilidad con tu sistema operativo. Lo único que nos interesa es que el resultado del programa sea correcto, la visualización se las pasamos porque es muy util para debugear y comprobar que la division que estás haciendo en el espacio está bien hecha.

Si tu programa hace todos los tests en menos de 10 segundos entonces no tienes nada de que preocuparte :)

**Comment by pstassara** [comment]
Bacán, gracias!
