### ISSUE TITLE
Tarea 1, duda con intersecciones.

### ISSUE THREAD

**Issue by tocococa** [IIC2133-PUC/2020-2#102]
hola! tengo la impresión que me puede estar pasando esto, que tengo dos segmentos que se juntan en el límite de dos cajas, y aunque la partícula en la simulación normal rebota con los dos segmentos (y luego se desempata), en mi implementación rebota solo con uno. ¿tiene sentido o mi bug será otro?
![image](https://user-images.githubusercontent.com/5317897/93033460-c4cc8680-f60c-11ea-89cf-13cea27b731a.png)

**Comment by vichoeq** [comment]
Eso no tiene mucho sentido: si efectivamente la particula choca con los dos segmentos, entonces deberia chocar con ambas cajas.

Consejo para debugear: en la función de ver colision particula x árbol, desactiva la parte que descarta el nodo actual si la particula no choca con la caja. Eso debería hacer que se revisen TODOS los nodos del árbol -> todas las hojas -> todos los segmentos. 

Si aun asi sigue fallando, es posible que 
1) Hayas perdido alguno de los segmentos en la construcción del árbol
2) Estes haciendo mal el desempate

**Comment by tocococa** [comment]
Hmmm, yap. Ahora que lo mencionas puede ser que el problema esté en la función de búsqueda, porque también me pasa que cuando tengo una colisión en el límite de las dos cajas a veces la partícula se queda atrapada.

No creo que esté perdiendo segmentos, porque el otro bug que tengo es que no colisiona con segmentos muy largos, pero solo si el ángulo es muy abierto, si el ángulo en que colisiona es más cerrado si rebota como debería.

**Comment by vichoeq** [comment]
Revisa entonces que todos los vértices de tus segmentos enten contenidos dentro de la caja:

(xmin,ymin) <= (x,y) <= (xmax,ymax)

**Comment by tocococa** [comment]
Revisé eso (pintando los vértices), y lo que me pasa es más o menos esto: 
![image](https://user-images.githubusercontent.com/22779371/93034287-f4c95900-f60f-11ea-8b61-7eb953ab9d4f.png)
Donde a veces rebota y a veces no (verde es que está contenido en una caja y rojo que registró una colisión)

**Comment by tocococa** [comment]
Para lo posterioridad (y si alguien más lee este hilo), mi función de búsqueda sobre el árbol estaba mala, por no decir otra cosa.

**Comment by fernandovegauc** [comment]
holaaa, donde estaba tu error? me está pasando exactamente lo msimo :(

**Comment by tocococa** [comment]
Holaa, eran varias cosas, 1) La forma en que buscaba intersecciones entre segmentos y cajas aabb estaba mala y esto hacía que las cajas quedaran mal definidas 2) Estaba ajustando mal el tamaño de las cajas en función del máximo y mínimo de los segmentos contenidos y 3) La función de búsqueda sobre el árbol estaba mala.
