### ISSUE TITLE
[Tarea 1] Analisis - Es necesario crear tests?

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#105]
Hola, en la tarea 1 se pide comparar el efecto de los parametros FPS, se puede hacer esto con solo los tests dados? (por lo que veo, la cantidad de segmentos no suele ser la misma, lo que dificulta la comparación. Ademas todos tienen la misma cantidad de frames)

**Comment by vichoeq** [comment]
Si, está bien que uses solo los tests dados :)

**Comment by Marialuisaclaro** [comment]
Hola! Y debemos hacer un análisis respecto a los parametros FPS de cada test y sus resultados? O solo considerar que con cada test tenemos misma cantidad de FPS para ambos programas?
