### ISSUE TITLE
[Tarea 1] Tests y evaluación

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2133-PUC/2020-2#106]
Hola! "Terminé" mi código y me gustaría saber si lo que hago está bien o mal y no se muy bien como hacerlo. Se que puedo dibujar mis cajas, pero al dibujarlas nose si están bien dibujadas porque nose como deberían ser.
Tampoco se si conviene probar y debuggear con los archivos demo o test.
Por último, cuanto es el tiempo estimado que se debería demorar nuestro programa en todos los tests?

Gracias!

**Comment by yerkko** [comment]
Hola, como dice el enunciado, cada test debe tomar menos de 10 segundos y los archivos de demo no se utilizarán para evaluar. 
Los tests se calibraron para que la pauta los resuelva en menos de 2 segundos, por lo que tienen bastante tiempo de margen.

Por otra parte, para revisar que entregues el output correcto puedes utilizar el comando diff.

**Comment by nmcin** [comment]
Hola! Habrá servidor para probar nuestro programa como en la t0?

**Comment by caespinoza5** [comment]
@nmcin Favor revisar el anuncio publicado el 07-09-2020 14:00 en siding

**Comment by nmcin** [comment]
Gracias!
