### ISSUE TITLE
Tarea 1 - bordes del mapa son parte de segmentos?

### ISSUE THREAD

**Issue by kmhaller** [IIC2133-PUC/2020-2#107]
Hola, ¿los bordes del mapa se incluyen en los segmentos
(sim-> segments) que recibe el programa?

**Comment by yerkko** [comment]
No

**Comment by kmhaller** [comment]
Me refería a los segmentos que están en el borde del mapa,
¿esos si los incluye o no?

**Comment by yerkko** [comment]
Los únicos archivos que tienen segmentos en el "borde" del mapa son los de demo, que como dice el enunciado, no se usarán para evaluar. Dicho esto, siempre tienes que añadir todos los segmentos del archivo al árbol.
