### ISSUE TITLE
Tarea 1: Informe

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2133-PUC/2020-2#110]
Hola! como en esta tarea el código es propio tenemos que explicar detalladamente cual es el algoritmo que utilizamos? podemos utilizar psuedo-codigo para explicar? El/La ayudante estara viendo el codigo que entregamos para explicar nuestro informe, etc?

Muchas gracias por la atención

**Comment by yerkko** [comment]
Incluye todo lo que consideres necesario con tal de que se entienda tu implementación, puede ser pseudocódigo o la implementación misma (los fragmentos importantes). Quien corrija no estará viendo tu repo al leer el informe.
