### ISSUE TITLE
Tarea 1 Complejidad del programa

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2133-PUC/2020-2#111]
Hola! Para el informe cuando piden la complejidad para la ejecución del programa total debemos incluir todo lo que hace main.c?
Debemos incluir la inicialización de la simulación y la liberación de memoria? o es solo inicializar arbol + calculo de posición de particulas (for de frames, for de particulas y busqueda en arbol)?
Gracias!

**Comment by yerkko** [comment]
Incluye todos tus supuestos, mientras sean razonables, **justificados** y el cálculo esté bien, no habrá problema.
