### ISSUE TITLE
Tarea 1 - Complejidad - Búsqueda en el árbol

### ISSUE THREAD

**Issue by humbertoortuzar** [IIC2133-PUC/2020-2#112]
Hola! Para calcular la segunda complejidad, puedo considerar que las cajas no se encuentran solapadas o debo considerar que una partícula puede encontrarse en más de una caja hija (left or right)?

Saludos!

**Comment by yerkko** [comment]
Puedes asumir lo que consideres necesario en el análisis, sin embargo, deben ser suposiciones explicitadas, justificadas y no contradecir lo solicitado.
