### ISSUE TITLE
Análisis - Tamaño hojas

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2133-PUC/2020-2#114]
Para el apartado de análisis del informe nos piden calcular la complejidad en notacion O para crear y buscar. Para ambos casos debemos suponer la misma cantidad de segmentos por hojas? cual tiene que ser esa cantidad?
O consideramos el peor escenario para crear un arbol de determinada forma y luego el peor escenario para buscar en la peor forma de arbol?

Gracias!

**Comment by yerkko** [comment]
Es parte del trabajo determinar cuáles son los factores a considerar y entender los efectos en la complejidad de los puntos pedidos.
