### ISSUE TITLE
Complejidad de la busqueda

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2133-PUC/2020-2#115]
Hola, estaba pensando en el peor caso para la búsqueda dentro del árbol, pero no estoy seguro si es posible que tenga que recorrer todos los nodos hojas en una búsqueda, ya que si es así la complejidad de la búsqueda sería la misma que en el algoritmo inicial. Yo creo que no es posible, pero tampoco se como argumentarlo, ya que es posible que una caja se superponga por encima de otra.

**Comment by yerkko** [comment]
Es parte de tu trabajo determinar cuál es el caso a estudiar para determinar la complejidad en notación bigO.
