### ISSUE TITLE
Complejidad algoritmo median

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2133-PUC/2020-2#117]
Hola! Si utilizamos el algoritmo median visto en clases para formar el árbol, para el cálculo de complejidad: ¿utilizamos su peor caso O(n^2) o su caso promedio O(nlogn)? Entiendo que estemos calculando la notación O de complejidad para el algoritmo, pero me pasa que considerando el peor caso de median mi algoritmo se supone que queda de orden mayor al naive, lo que no tiene mucho sentido(O estoy haciendo los calculos mal?)

Saludos y gracias!

**Comment by yerkko** [comment]
Hola, es parte de la tarea determinar el caso a analizar. Sólo tienes que ser consistente y estará correcto.
Con respecto a si estás haciendo mal el cálculo, sí; hay un factor **muy** importante que no estás considerando.
