### ISSUE TITLE
Tarea 1 Problema al compilar

### ISSUE THREAD

**Issue by MINGOD24** [IIC2133-PUC/2020-2#118]
Hola, cuando hago make a mi tarea me sale el siguiente error:
**make: warning:  Clock skew detected.  Your build may be incomplete.**
**make: Warning: File 'src/simulate/kd-tree.h' has modification time 43927 s in the future**

Lo busque en internet pero no encontre nada que me hiciera sentido. Alguien sabe que puede ser?

**Comment by cjones27** [comment]
Hola! Por lo que pude investigar, ese error ocurre cuando se desincroniza el reloj de tu computador. Al parecer, el makefile hace cambios incrementales al compilar (es más rápido que compilar desde cero). Por lo tanto, si el reloj está fuera de sincronía, puede generar el warning al compilar ya que el compilador no sabe bien cuáles archivos compilar de nuevo y cuáles no. 

Intenta usar `make clean` en el terminal. Este comando borra los antiguos archivos compilados y vuelve a usar `make`.
Avisanos si funciona!

**Comment by MINGOD24** [comment]
Hola, sii encontre lo mismo que tu cuando busque pero me parece raro porque el reloj esta bien. Trate de hacer el make clean y reintente hacer make pero sigo con el mismo problema. :(

**Comment by cjones27** [comment]
Aunque sea un poco pasado de la hora, quería dejarte esta opción para que la pruebes. Pero antes, 2 cosas importantes antes de ejecutar los comandos.

1. **Sube lo que actualmente tienes a tu repositorio de git** (por cualquier cosa es un backup)
2. Corre los comandos especificamente **dentro de la carpeta de la tarea**

``` 
find . -type f | xargs -n 5 touch
make clean
make
```
Ojalá funcione!
