### ISSUE TITLE
Tarea 1

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2133-PUC/2020-2#119]
Hola! Estoy teniendo problemas al abrir el simulador pero no cuando agrego el --novis. ¿Por qué podría ser?

![image](https://user-images.githubusercontent.com/48481728/93776620-20dd6f00-fbfa-11ea-85ac-a25c115303ca.png)

**Comment by dvogaz** [comment]
Puede ser el visualizador, revisaste esto [https://github.com/IIC2133-PUC/2020-2/blob/master/Gu%C3%ADas/Setup/3.0%20GTK.md](guía de instalación)?

**Comment by dvogaz** [comment]
Puede ser el visualizador, revisaste esto [https://github.com/IIC2133-PUC/2020-2/blob/master/Gu%C3%ADas/Setup/3.0%20GTK.md](url)?

**Comment by Ignaciomendezp** [comment]
No es eso, el visualizador me funciona perfectamente sin ejecutar mi código. Volví a instalar lo mencionado en la guía de todos modos pero me pasa lo mismo. 😞
