### ISSUE TITLE
Subir Informe T1

### ISSUE THREAD

**Issue by martinrtc** [IIC2133-PUC/2020-2#122]
Hola! quería saber donde se sube el informe, ya que el enunciado sale que es en el siding pero el cuestionario esta cerrado.

**Comment by pstassara** [comment]
Según el último anuncio de Vicente, en caso de optar por la entrega atrasada hay que subirlo al repositorio :)

**Comment by caespinoza5** [comment]
Tal como dice @pstassara se debe subir al repositorio.

Saludos,
Cristóbal
