### ISSUE TITLE
📜 Dudas I1

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-2#124]
# Instrucciones generales

* La prueba considera que tienen acceso a internet, libros y clases. Si van a usar este material, expresenlo en sus propias palabras.
* La prueba es individual. No esta permitido preguntar ni responder acerca de la prueba a nadie que no sea parte del cuerpo docente del curso.
* El módulo de clases será usado para hacer una sesión activa de dudas del enunciado mediante zoom.
* Durante el resto del tiempo, cualquier duda que tengan debe ser publicada aquí como issue. No responderemos correos ni mensajes directos.
* Los ayudantes iremos respondiendo las dudas tan rápido como podamos.
* El formato de entrega es por PDF. Puede contener lo siguiente:
    * Texto digital (Word, Latex)
    * Texto escrito a mano (por favor que la letra sea clara)
    * Algoritmos y diagramas *dibujados* en papel. (Edit: Herramientas digitales son bienvenidas, si quieren tomarse el tiempo)
    * Usar Scanner o aplicaciones de celular como CamScanner para digitalizar lo que hagan a mano. Evitar fotografías.

## NO ESTÁN PERMITIDAS DUDAS QUE CONTENGAN UNA FORMA DE ABORDAR UN PROBLEMA, COMO "ESTA BIEN SI HAGO X?" O "ESTOY HACIENDO X PERO NO ME RESULTA"

# Dudas de zoom

### a)

* Quicksort va a llamar a partition con varios subarreglos del arreglo que buscas ordenar. Este arreglo es tal que cada vez que se llama partition este hace la máxima cantidad de intercambios posible.
* Por tiempo se refiere a complejidad.
* Esto es partition en arreglos, en particular la rutina partition para arreglos que vimos en clases (está en las diapos de quicksort)
* Se refiere al mejor caso de Quicksort.
* Quicksort no tiene nada que ver con las inversiones en un arreglo.

### b)

* Los pivotes p y q son elementos del subarreglo a particionar.
* **Puedes hacer el pseudocódigo para trabajar con listas en lugar de arreglos [Dale las gracias a Tomás]**
* Debes analizar al menos el peor caso del algoritmo. Los demás no importan.

### a)

* La prioridad de un elemento sería su clave en el árbol.
* La cantidad de elementos en el ABB también es n.
* min-heap asigna prioridad inversamente proporcional al valor numerico de una clave: mientras más bajo es un número más prioridad tiene.
* No puedes asumir nada acerca del ABB además de que cumple con la propiedad de ABB.
* Tu algoritmo puede destruir el ABB si lo estimas necesario.

### b)

* No es exactamente n/2 ya que n podría ser impar. Trabaja con el piso o el techo segun lo que te acomode.
* El tipo de heap (min-heap / max-heap) no deberia afectar tu respuesta.
* No puedes ni deberías modificar los elementos del heap.
* El heap es un heap.

### a)

* T tiene que seguir siendo ABB luego de hacer la transformación
* No es necesario balancear (y el árbol no necesariamente estaba balanceado en un principio)
* Puedes hacer el algoritmo asumiendo que ya tienes un puntero al elemento que quieres dejar como raíz: el algoritmo a partir de ahi tambien es O(h)

### b)

* T1 y T2 no necesariamente están balanceados.
* El criterio de balance que debe tener el árbol resultante puedes elegirlo tu.
* Puedes asumir que todas las claves son distintas

### b)

* El árbol rojo-negro lo más desbalanceado posible se define de manera homologa a el AVL más desbalanceado posible.

**Comment by vichoeq** [comment]
@Alonsinho1 no, se refiere a que, si el máximo posible de intercambios que hacer partition para un arreglo de **m** elementos es **f(m)**, entonces el numero de intercambios que hace partition en el mejor caso de quicksort se plantea como una fracción de **f(m)**, como **f(m) / k **

**Comment by JupaOlivares** [comment]
En la pregunta  3, puedo asumir que encontrar el padre de un nodo es O(1)? o sea que el nodo tiene almacenado quien es su padre

**Comment by vichoeq** [comment]
@JupaOlivares sí, pero ponlo explicito en tu prueba.

**Comment by jnhasard** [comment]
@JupaOlivares Sí

**Comment by szabala** [comment]
En la pregunta 1, cuando nos preguntan si _quicker-sort_ es más eficiente que _quick-sort_, hay que justificarlo en distintos casos? Por ejemplo, en el caso X,  _quicker-sort_ es mas eficiente que _quick-sort_. En el caso Y ...

**Comment by Arodriguez14** [comment]
En la 1a, cuando de la fracción de intercambios del mejor caso vs el caso descrito en el enunciado, es en una llamada cualquiera de particion? O en total del quicksort completo?

**Comment by Arodriguez14** [comment]
En la 1a, cuando se habla de la fracción de intercambios del mejor caso vs el caso descrito en el enunciado, es en una llamada cualquiera de particion? O en total del quicksort completo?

**Comment by vichoeq** [comment]
> 
> 
> En la pregunta 1, cuando nos preguntan si _quicker-sort_ es más eficiente que _quick-sort_, hay que justificarlo en distintos casos? Por ejemplo, en el caso X, _quicker-sort_ es mas eficiente que _quick-sort_. En el caso Y ...

Hola, de las Dudas de zoom arriba:

> Debes analizar al menos el peor caso del algoritmo. Los demás no importan.

**Comment by vichoeq** [comment]
> En la 1a, cuando de la fracción de intercambios del mejor caso vs el caso descrito en el enunciado, es en una llamada cualquiera de particion? O en total del quicksort completo?

Hola, se refiere a que todas las llamadas a partition hacen la misma fracción de intercambios. 

Si ves el comentario que puse arriba: https://github.com/IIC2133-PUC/2020-2/issues/124#issuecomment-703798815

El valor de **k** deberia ser el mismo para cada llamada a partition.

**Comment by Alonsinho1** [comment]
@vichoeq Si expreso esta fraccion utilianzdo cardinalidaes de conjuntos, contaria como si estoy dividiendo entre constantes? Que si uno llego a expresiones que ambas dependen de distintos factores de N, no seria posible expresalro como una constante por lo que tengo entendido.

Creo no haber rompido alguna regla del foro, sin embargo, disculpas si lo hice

**Comment by vichoeq** [comment]
@Alonsinho1 claro pero si bien el **m** depende de **n**, el **k** depende del orden en el que vienen los datos; y eso no depende de **n**.

**Comment by vichoeq** [comment]
Recuerda que esto es lo que pasa con quicksort al ejecutarlo con un arreglo **particular**

**Comment by Aloncarrasco** [comment]
Puedo usar cosas demostradas en la ayudantía?

**Comment by vichoeq** [comment]
@Aloncarrasco si

**Comment by Juan379** [comment]
En la 1a), el algoritmo partition que vimos en clase no incluye swaps, solamente hace comparaciones e inserta en dos listas externas para determinar la posicion correcta del pivote. Entonces, intercambios = comparaciones?

**Comment by ifieldhouse** [comment]
@Juan379 Cuidado que se vieron _dos_ variaciones de partition: el que describes, y uno in-place.

**Comment by javieranavarrete** [comment]
2.a cuando dice escribe un algoritmo, esto es necesariamente en pseudocodigo? O puedo explicar la logica como se debe hacer x cosa, luego y, después  se repite desde tal paso.

**Comment by yerkko** [comment]
@javieranavarrete Pseudocódigo

**Comment by vichoeq** [comment]
Agregando a lo que dijo Ian, el algoritmo in-place es para ARREGLOS.

**Comment by tomasalvarez13** [comment]
Hola, sobre el algoritmo para listas,asumimos que la concatenacion de éstas es O(1)?

**Comment by vWing7** [comment]
En la 1.a, cuando habla de mejor caso, se refiere a mejor caso usando el mismo partition que siempre hace la mayor cantidad de intercambios, al caso en que siempre le "achunto" con los pivotes, o algun otro?

**Comment by Juan379** [comment]
Ok perfecto, entonces follow up question. En partition de arreglos, si es que se swappean dos elementos que son iguales, esto cuanta como swap? Ya que en verdad no habría cambio quedaría igual.

**Comment by tomasalvarez13** [comment]
En la 1.b podemos asumir que no hay elementos repetidos?

**Comment by ifieldhouse** [comment]
@tomasalvarez13 No. Al igual que quicksort, el algoritmo debe ser capaz de manejar elementos repetidos.

**Comment by tomasalvarez13** [comment]
osea que pueden haber elementos iguales al pivote?

**Comment by cahinostroza** [comment]
En la 2b revisar se refiere a ver el valor del nodo o a entrar en la estructura de él? Porque para un heap de sólo 3 nodos, primero reviso si la raiz tiene hijos y luego veo los valores de cada hijo, en ese caso revisé 3 nodos, pero sólo vi el valor de 2 de ellos.

**Comment by Alonsinho1** [comment]
En la 1.2 si tengo un arreglo en el cual tengo solamente numeros repetidos no podria escoger un pivote tal que p-q y por ende este algoritmo no podria relizarse este algoritmo y por ende seria incorrecto.

Puedo asumir que dentro de un arreglo siempre existe almenos un elemento mas grande que el otro?

**Comment by Marialuisaclaro** [comment]
3.
Hay que demostrar correctitud de los algoritmos que utilicemos en a y b?
Las preguntas a) y b) están relacionadas? o son independientes?

**Comment by MINGOD24** [comment]
En la 1.a si el indice es el mismo lo contamos como swap?

**Comment by jalliende** [comment]
en la 3 b al realizar un pseudocodigo tiene que tipo C? o puedo ocupar código tipo python?

**Comment by ifieldhouse** [comment]
@Juan379 @MINGOD24 Sí. De igual manera estás realizando la sentencia `swap`.

**Comment by yerkko** [comment]
> Hay que demostrar correctitud de los algoritmos que utilicemos en a y b?
> Las preguntas a) y b) están relacionadas? o son independientes?

Tienes que justificar tus respuestas. (a) y (b) son independientes.

**Comment by yerkko** [comment]
@jalliende Pseudocódigo similar Como el de las diapositivas de clases.

**Comment by MINGOD24** [comment]
En la 4a, debemos explicar como se logra, o debemos demostrar a traves de inducción?

**Comment by kylevon** [comment]
> En la 4a, debemos explicar como se logra, o debemos demostrar a traves de inducción?

Nota que en la pregunta no piden una demostración, pese a eso escribe tu razonamiento de por qué funciona tu método. Una justificación a esta pregunta usando inducción es innecesaria.

**Comment by clementeross** [comment]
En la pregunta 4 se habla de un AVL lo más desbalanceado posible. Sin embargo, el hecho de que sea un AVL ya lo hace cumplir ciertas propiedades de balanceo, si no, podría ser un ABB cualquiera. Tomamos en cuenta estas propiedades que diferencian un AVL de un ABB?

**Comment by kylevon** [comment]
> En la pregunta 4 se habla de un AVL lo más desbalanceado posible. Sin embargo, el hecho de que sea un AVL ya lo hace cumplir ciertas propiedades de balanceo, si no, podría ser un ABB cualquiera. Tomamos en cuenta estas propiedades que diferencian un AVL de un ABB?

Sí

**Comment by raimundoloeser** [comment]
En la 1 b) se asume que los pivotes no tienen elementos iguales a ellos? por que en el enunciado sale: "los elementos menores que p, el pivote p, los entre p y q, el pivote q, y los mayores que q" O escribimos pseudocodigo tambien para cuando son iguales

**Comment by jalliende** [comment]
en la 2 a es necesario demostrar la complejidad? o solo correctitid?

**Comment by kylevon** [comment]
> En la 1 b) se asume que los pivotes no tienen elementos iguales a ellos? por que en el enunciado sale: "los elementos menores que p, el pivote p, los entre p y q, el pivote q, y los mayores que q" O escribimos pseudocodigo tambien para cuando son iguales

Esta pregunta ya se respondió por Ian.

>  No. Al igual que quicksort, el algoritmo debe ser capaz de manejar elementos repetidos.

**Comment by kylevon** [comment]
> en la 2 a es necesario demostrar la complejidad? o solo correctitid?

Te recomiendo encarecidamente leer las instrucciones de la prueba, en estas aparece:

> **Si una pregunta pide que hagas algo en una complejidad específica, entonces
debes justificar por qué tu respuesta tiene esa complejidad. Si la complejidad no es la que se pide, entonces el puntaje máximo que puedes tener en esa letra es 1pt**

**Comment by tomasalvarez13** [comment]
Puedo asumir que existe  algun tipo de for para iterar sobre nodos de un ABB? O tengo q implementar de manera recursiva el for

**Comment by kylevon** [comment]
> ABB

No puedes asumir esto por la variedad combinatorial de formas de recorrer un ABB.

**Comment by javieranavarrete** [comment]
Se puede contestar por ejemplo la a) de la 1 (no la b), y la a) de la 2 y no la b. Y que eso sea revisado?. O para que cuente debe ser a y b de la misma pregunta?

**Comment by cjones27** [comment]
> Hola, sobre el algoritmo para listas,asumimos que la concatenacion de éstas es O(1)?

@tomasalvarez13 Esto es parte de la materia, pero si, la concatenación de listas es O(1).

**Comment by yerkko** [comment]
@javieranavarrete No

**Comment by arpincheira** [comment]
En la 4a,  consideramos solamente el pintar un árbol estático? Es decir, dado un AVL transformarlo a rojo, negro o debemos considerar también como lo pintaríamos durante procesos de inserción y balance?

**Comment by kylevon** [comment]
> En la 4a, consideramos solamente el pintar un árbol estático? Es decir, dado un AVL transformarlo a rojo, negro o debemos considerar también como lo pintaríamos durante procesos de inserción y balance?

Se refiere a pintar un estado particular del árbol. No tienen que considerar los procesos de inserción y balance para la 4a.

**Comment by chris-carstens** [comment]
Hola! En la pregunta 1.a, al pedir ¿Qué fracción del mayor número posible de intercambios se harían en el mejor caso? , basta con entregar la proporción de las complejidades para el número de intercambios en ambos casos, o llegar a la expresión exacta?
Gracias!

**Comment by jalliende** [comment]
En la pregunta 4 se puede modificar la estructura de un AVL?

**Comment by Alonsinho1** [comment]
En la pregunta 2 es necesario entregarlo como un heap version arbol o simplemente podemos entregar el heap como array?

**Comment by jnhasard** [comment]
> En la pregunta 4 se puede modificar la estructura de un AVL?

Te refieres a si en la 4.a puedes cambiar la estructura? en ese caso no, solo tienes que explicar como decidir de que color pintar cada nodo, sin cambiarle nada más al árbol

**Comment by nhbravo** [comment]
Para entregar pseudocodigo, puede ser escrito en un editor de texto e insertado en el latex como una imagen? Por simplicidad

**Comment by jnhasard** [comment]
> Para entregar pseudocodigo, puede ser escrito en un editor de texto e insertado en el latex como una imagen? Por simplicidad

Sí, eso si no uses nada muy especifico de algún lenguaje. Escribe pseudocódigo

**Comment by juakoke** [comment]
Puedo determinar los atributos que tendrá el nodo de un ABB?

**Comment by jnhasard** [comment]
> En la pregunta 2 es necesario entregarlo como un heap version arbol o simplemente podemos entregar el heap como array?

> Puedo determinar los atributos que tendrá el nodo de un ABB?

Si asumen algo, especifíquenlo

**Comment by cjones27** [comment]
> Para entregar pseudocodigo, puede ser escrito en un editor de texto e insertado en el latex como una imagen? Por simplicidad

Si, por supuesto. La única condición es que sea claro y en formato pdf.

**Comment by lothardp** [comment]
> Hola! En la pregunta 1.a, al pedir ¿Qué fracción del mayor número posible de intercambios se harían en el mejor caso? , basta con entregar la proporción de las complejidades para el número de intercambios en ambos casos, o llegar a la expresión exacta?

¿A que te refieres con la proporción de las complejidades? Lo que se pide es la fracción del mayor número posible de intercambios se harían en el mejor caso, es decir, la proporción entre el número de intercambios que se hacen en el mejor caso y el mayor número posible de intercambios.

**Comment by tomasalvarez13** [comment]
en la 1b cuando tenemos que elegir los pivotes p y q, nos tenemos que preocupar que p este posicionado antes que q,o que el valor de p sea menor que el valor de q? Gracias

**Comment by lisraelrat1** [comment]
En la 4a, la profundidad la dejamos expresada en términos de altura o nodos?

**Comment by vichoeq** [comment]
@lisraelrat1 conoces la altura, pero no la cantidad de nodos. Lo dejo a tu criterio.

**Comment by vichoeq** [comment]
@vWing7  
> En la 1.a, cuando habla de mejor caso, se refiere a mejor caso usando el mismo partition que siempre hace la mayor cantidad de intercambios, al caso en que siempre le "achunto" con los pivotes, o algun otro?

Eso es materia de clases, deberias saber qué implica que quicksort esté en su mejor caso.

**Comment by vichoeq** [comment]
@cahinostroza  

> En la 2b revisar se refiere a ver el valor del nodo o a entrar en la estructura de él? Porque para un heap de sólo 3 nodos, primero reviso si la raiz tiene hijos y luego veo los valores de cada hijo, en ese caso revisé 3 nodos, pero sólo vi el valor de 2 de ellos.

Recuerda como se implementan los heap en la práctica: cuantos datos es estrictamente necesario revisar independiente de la implementación?

**Comment by chris-carstens** [comment]
En pseudocódigo, podemos utilizar un estilo append, que nos agregue elementos al final de un arreglo? (para no estar pasando índices y n)

**Comment by vichoeq** [comment]
@chris-carstens ojo que los arreglos no permiten esa operacion en tiempo eficiente. Si vas a usarla tienes que especificar por qué funciona y por que no te rompe la complejidad del algoritmo.

**Comment by vichoeq** [comment]
@chris-carstens basicamente tendrias que explicar como está implementado el append.

**Comment by lothardp** [comment]
> en la 1b cuando tenemos que elegir los pivotes p y q, nos tenemos que preocupar que p este posicionado antes que q,o que el valor de p sea menor que el valor de q? Gracias

Al elegir tus pivotes p y q debes asegurarte que p < q (como dice el enunciado).

**Comment by chris-carstens** [comment]
@vichoeq pero tipo hacer arr[n-1] = K, y para no actualizar índices que pasaré en la recursión (para insertar desde atrás para adelante) decir simplemente que arr.append(k), en teoría es igual de eficiente o no?

**Comment by nhbravo** [comment]
> @chris-carstens ojo que los arreglos no permiten esa operacion en tiempo eficiente. Si vas a usarla tienes que especificar por qué funciona y por que no te rompe la complejidad del algoritmo.

Y si, en caso contrario, fuera insertar en el inicio de un arreglo?

**Comment by vichoeq** [comment]
> @vichoeq pero tipo hacer arr[n-1] = K, y para no actualizar índices que pasaré en la recursión (para insertar desde atrás para adelante) decir simplemente que arr.append(k), en teoría es igual de eficiente o no?

@chris-carstens no, recuerda que los arreglos son de tamaño fijo. Una cosa es escribir un valor en la primera celda vacía del arreglo, y otra cosa muy distinta es hacer crecer el arreglo.

**Comment by mscuturrufo** [comment]
En la 3.b es necesario pseudo codigo o solo enlistar lo que hay que hacer?

**Comment by vichoeq** [comment]
> > @chris-carstens ojo que los arreglos no permiten esa operacion en tiempo eficiente. Si vas a usarla tienes que especificar por qué funciona y por que no te rompe la complejidad del algoritmo.
> 
> Y si, en caso contrario, fuera insertar en el inicio de un arreglo?

@nhbravo lo mismo, tienes que explicar como funciona tu funcion por detrás.

**Comment by chris-carstens** [comment]
> > @vichoeq pero tipo hacer arr[n-1] = K, y para no actualizar índices que pasaré en la recursión (para insertar desde atrás para adelante) decir simplemente que arr.append(k), en teoría es igual de eficiente o no?
> 
> @chris-carstens no, recuerda que los arreglos son de tamaño fijo. Una cosa es escribir un valor en la primera celda vacía del arreglo, y otra cosa muy distinta es hacer crecer el arreglo.

@vichoeq  Claro, de hecho a eso me refiero, a que tengo un arreglo de tamaño n, y como estoy ejecutando mis códigos con funciones, en general me facilita decir que lo agregaré en la última posición vacía, en vez de decir que lo posicionaré en la posición i. A eso me refería con el append más que agrandar el arreglo .

**Comment by vichoeq** [comment]
> En la 3.b es necesario pseudo codigo o solo enlistar lo que hay que hacer?

Un algoritmo es una secuencia ordenada de pasos. Una lista de pasos ordenada que permita resolver el problema es suficiente.

**Comment by vichoeq** [comment]
@chris-carstens mientras la definas bien no debería haber problema. Pero ojo que si está mal definida podría disparar la complejidad de tu algoritmo.

**Comment by dgfluxa** [comment]
> En la 1.2 si tengo un arreglo en el cual tengo solamente numeros repetidos no podria escoger un pivote tal que p<q, por ende este algoritmo no podria relizarse y por ende seria incorrecto.
> 
> Puedo asumir que dentro de un arreglo siempre existe almenos un elemento mas grande que el otro?

Tengo esta misma duda, creo que aún no la han respondido.

**Comment by cahinostroza** [comment]
Pueden dar un ejemplo de arbol rojo negro lo más desbalanceado posible para la pregunta 4b?

**Comment by cahinostroza** [comment]
Para la pregunta 2b puedo asumir que el heap está lo más compacto posible?, por ejemplo no tengo un heap con un hijo de altura 1 y con el otro de altura gigantesca?

**Comment by vichoeq** [comment]
@cahinostroza 
> Pueden dar un ejemplo de arbol rojo negro lo más desbalanceado posible para la pregunta 4b?

No. De eso se trata la pregunta.

**Comment by vichoeq** [comment]
> > En la 1.2 si tengo un arreglo en el cual tengo solamente numeros repetidos no podria escoger un pivote tal que p<q, por ende este algoritmo no podria relizarse y por ende seria incorrecto.
> > Puedo asumir que dentro de un arreglo siempre existe almenos un elemento mas grande que el otro?
> 
> Tengo esta misma duda, creo que aún no la han respondido.

Como el enunciado dice p < q, puedes asumir para efectos del analisis que todos los elemenos serán distintos.

**Comment by vichoeq** [comment]
@cahinostroza te respondi arriba. https://github.com/IIC2133-PUC/2020-2/issues/124#issuecomment-703901572

**Comment by rjdelrio** [comment]
hola

**Comment by vichoeq** [comment]
> en la pregunta 2.a use pseudocodigo para contestar parte de la justificación, es posible usar listas para simplificar un poco el código o tengo que usar arreglos

@rjdelrio puedes usar lo que quieras, pero no me hago responsable de como eso impacte la complejidad de tu algoritmo.

**Comment by MINGOD24** [comment]
Para los pseudocodigos puedo escribir lo que haria el codigo enves de hacer un pseudocodigo como hemos visto en clases? o debe ser de esta ultima manera?

**Comment by NicolasLahsen** [comment]
> Para los pseudocodigos puedo escribir lo que haria el codigo enves de hacer un pseudocodigo como hemos visto en clases? o debe ser de esta ultima manera?

@MINGOD24 hola! debes escribirlo de forma que se explicite su complejidad.

**Comment by Tomas-Ira** [comment]
En la pregunta 2, debo explicar como obtengo el largo actual del heap creado en un momento dado, o lo puedo obtener nomás.

**Comment by tocococa** [comment]
Hola! La P0 dónde se entrega? no tiene cuestionario en siding.

**Comment by NicolasLahsen** [comment]
> En la pregunta 2 a, debo explicar como obtengo el largo actual del heap creado en un momento dado, o lo puedo obtener nomás.

@Tomas-Ira  Lo debes explicar

**Comment by Marialuisaclaro** [comment]
4. podemos asumir h par?

**Comment by yerkko** [comment]
@tocococa Está en el enunciado

**Comment by ifieldhouse** [comment]
@Marialuisaclaro No es necesario asumirlo.

**Comment by lucasvsj** [comment]
Tengo una duda simple en la **2.b**, cuando dicen que **p < q**, puede pasar que el **indice** de **p** sea **mayor** que el de **q**. O este caso no existe?

**Comment by Marialuisaclaro** [comment]
@ifieldhouse  en la 4.b no puedo ni es necesario asumirlo?

**Comment by lothardp** [comment]
> Tengo una duda simple en la **1.b**, cuando dicen que **p < q**, puede pasar que el **indice** de **p** sea **mayor** que el de **q**. O este caso no existe?

Si puede pasar. p y q son dos elementos del arreglo que tu seleccionas para ser tus pivotes, que cumple con que p < q.

**Comment by gejohow** [comment]
3.
Cuando se hace merge de dos trees los nodos que estan en la misma posición tienen que sumar sus valores? O la idea es que se arme un nuevo árbol con todos los valores de T1 y T2 y estos aparezcan una sola vez?

**Comment by kmhaller** [comment]
2. a) O(n) tiene que ser la cantidad de iteraciones del algoritmo?

**Comment by cjones27** [comment]
> Cuando se hace merge de dos trees los nodos que estan en la misma posición tienen que sumar sus valores? O la idea es que se arme un nuevo árbol con todos los valores de T1 y T2 y estos aparezcan una sola vez?

@gejohow La idea es que el abb resultante contenga los nodos de ambos árboles, T1 y T2.

**Comment by cjones27** [comment]
>     1. a) O(n) tiene que ser la cantidad de iteraciones del algoritmo?

@kmhaller La complejidad de tu algoritmo que resuelve lo solicitado debe ser O(n).

**Comment by kmhaller** [comment]
en la 4 a) puedo asumir que sé la profundidad maxima y minima del nodo derecho e izquierdo de un nodo al ir pintando?

**Comment by StroveLight** [comment]
en la 1a, se consideran los intercambios con la misma casilla? (con sigo misma)

**Comment by FeBalla** [comment]
podemos asumir como implementadas las funciones de rotaciones?

**Comment by yerkko** [comment]
@FeBalla 

no

**Comment by StroveLight** [comment]
en la 3a, podemos asumir como implementado la funcion de llegar a un nodo de un ABB?

**Comment by yerkko** [comment]
@StroveLight está en el faq

**Comment by StroveLight** [comment]
> en la 1a, se consideran los intercambios con la misma casilla? (con sigo misma)

tambien está en la faq?

**Comment by Aloncarrasco** [comment]
En cada pregunta subí la prueba completa. ¿Da lo mismo?

**Comment by yerkko** [comment]
> > en la 1a, se consideran los intercambios con la misma casilla? (con sigo misma)
> 
> tambien está en la faq?

No, pero en una consulta que hicieron más arriba. **Sí** se considera.

**Comment by yerkko** [comment]
> En cada pregunta subí la prueba completa. ¿Da lo mismo?

Nos harás el trabajo un poco más difícil, pero no hay penalización

**Comment by dgfluxa** [comment]
En la 3.a que cambios deben haber finalmente en el árbol resultante? Se reemplaza el valor de la raíz por el del elemento, solo se cambia el valor de la raiz por el del elemento (y este valor queda duplicado en la posición original) o no importa el orden del árbol mientras la raiz del árbol final tenga el valor del elemento??

**Comment by yerkko** [comment]
> En la 3.a que cambios deben haber finalmente en el árbol resultante? Se reemplaza el valor de la raíz por el del elemento, solo se cambia el valor de la raiz por el del elemento (y este valor queda duplicado en la posición original) o no importa el orden del árbol mientras la raiz del árbol final tenga el valor del elemento??

La restricción es que tiene que terminar siendo un ABB válido

**Comment by RositaMunoz** [comment]
ayudaa, se me cayó el internet y no pude subir mis respuestas, hay alguna forma de entregar aunque sea atrasada?

**Comment by caespinoza5** [comment]
@RositaMunoz envíame un correo a caespinoza5@uc.cl en cuanto puedas con tus respuestas

**Comment by StroveLight** [comment]
Hola, cuando volveran a abrir el discord?

**Comment by caespinoza5** [comment]
@StroveLight Se acaba de abrir 🙂

**Comment by jearaneda** [comment]
Mandé sin querer la P1 siendo que no había respondido esa pregunta (respondí P2, P3, P4). Siding no me dejó anular la entrega, puedo hacer algo para que no me corrijan esa por favor?

**Comment by vichoeq** [comment]
@jearaneda me mandaste un correo, no? Ya esta considerado.
