### ISSUE TITLE
[Tarea 2] Duda enunciado

### ISSUE THREAD

**Issue by fivaldivia** [IIC2133-PUC/2020-2#125]
Hola, en la tarea se está pidiendo crear un BSS balanceado con los datos que nos dan, luego implementar hash para buscar lo que se nos pide, y una hash table? Es que me enredé con el enunciado. Gracias!

**Comment by vichoeq** [comment]
Un BSS? Que sería un BSS?

**Comment by fivaldivia** [comment]
Un árbol binario*, perdón!

**Comment by vichoeq** [comment]
Efectivamente. Los datos que te damos representan un árbol binario **completo** (ojo que no es de busqueda). Estos árboles son muy faciles de representar en memoria, así que es poco lo que deberías implementar al respecto. (si no ves por qué, recomiendo que recuerdes todos los tipos de árboles que hemos visto)

Respecto a lo de hash, es parte de la tarea identificar cómo aplicarlo. Recomiendo:

* Pensar como resolver este problema sin ninguna estructura auxiliar, y fijate cual es la complejidad de hacerlo
* Identificar como aplicar diccionarios (en terminos generales) para problema **[parte del documento de diseño]** 
* En particular, identificar como aplicar tablas de hash para este problema.
* Diseñar una funcion de hash uniforme para sub-arboles que te permita aplicar tablas de hash para este problema  **[parte del documento de diseño]** 
* Probar empíricamente la distribución de tu funcion de hash **[parte del documento de diseño]** (se puede hacer teóricamente pero es mucho más dificil)
* Implementar el código

Recuerda que el enunciado mismo recomienda partir haciendo el documento de diseño.

¿Alguna duda?

**Comment by fivaldivia** [comment]
Ya perfecto, me queda más claro , gracias!

**Comment by fnberrios** [comment]
@vichoeq Es necesario que implemente los datos que me entregan del árbol binario en un árbol binario? Podría almacenarlos inmediatamente en un hash?

**Comment by vichoeq** [comment]
No hay reglas sobre como implementes nada en tus tareas. La única restriccion es que debes usar C y respetar el formato de input / output.

**Comment by fnberrios** [comment]
@vichoeq De acuerdo, gracias!

**Comment by fivaldivia** [comment]
Hola, en la parte de aplicar diccionarios hay que ver una implementación simple (como array por ejemplo), o se pide algo más como implementarlo con árboles u otros?

**Comment by vichoeq** [comment]
@fivaldivia recuerda la definicion de **diccionario** que vimos en clases... hay múltiples formas de implementarlos, pero todos proveen las mismas operaciones. La única diferencia entre distintos diccionarios (como ABB vs Tablas de Hash) es la complejidad de sus operaciones, además de funcionalidades adicionales (por ejemplo, un ABB permite recorrer las claves en orden, mientras que una tabla de hash no)

Eso es lo que tienes que responder: como usar un diccionario para este problema. Quizás tenga más sentido para ti pensarlo como resolver este problema en python usando los diccionarios que provee el lenguaje... ahi no te importa como están implementados por detrás, o si?

> Y otra pregunta estoy un poco enredada con el hash y el hash table... es posible que implemente un algoritmo que para cada árbol que se quiere buscar se creen distintas tablas de hash?

Todo es posible; la pregunta que tienes que hacerte es qué tan eficiente es ese approach, no si puedes hacerlo o no. (Y al final del dia, si te ayuda a resolver el problema más rapido o no aporta nada mas que ruido)

**Comment by cahinostroza** [comment]
@vichoeq como puedo probar empíricamente la distribución de la función de hash?

**Comment by vichoeq** [comment]
@cahinostroza lo vamos a ver este miércoles.

**Comment by RositaMunoz** [comment]
@vichoeq una pregunta sobre el tema de los diccionarios, cuando se pide indicar cómo solucionar el problema mediante diccionarios, se refiere a que toda la solución sea mediante esa estructura o esta puede ser parte de la solución?
Me explico, por ejemplo, que al implementar el diccionario, solo sea buscar en él y obtenga el resultado indicado o puede ser que lo ocupe, obtenga algo y después ocupe eso para obtener el resultado indicado?
Gracias de antemano!

**Comment by yerkko** [comment]
Puede ser parte de tu solución, sólo tienes que explicitarlo

**Comment by RositaMunoz** [comment]
gracias @yerkko ! (que rápido :0 )
