### ISSUE TITLE
[Tarea 2] No utilizar la función de hash de los sub árboles

### ISSUE THREAD

**Issue by cahinostroza** [IIC2133-PUC/2020-2#126]
Hola, si tengo una forma de hacer la función hash sin  ver los árboles hijos del árbol que le estoy calculando el hash, es decir de forma directa, estaría todo malo o habría sólo un descuento?

**Comment by kylevon** [comment]
¡Con tal de que lo puedas generar de manera incremental está bien! Para darte un ejemplo concreto que explica lo que es incremental, sin decir una forma de solucionar el problema en la tarea (como lo hace el enunciado al referirse específicamente a los hijos):

Consideremos la secuencia de fibonacci:

f(1) = 1
f(2) = 1
f(n) = f(n-2) + f(n-1)

Si necesitas asignar múltiples valores de fibonacci a distintos objetos, por ejemplo f(100) al objeto 1 y f(105) al objeto 2. En vez de calcular f(105) directamente sabiendo f(1) y f(2), usar el conocimiento que tienes de f(100) y f(99) permitiría ahorrarse muchos pasos y baja la complejidad de calcular un número de fibonacci específico conociendo sus dos antecesores de O(fib(n)) a O(n). (La función de recurrencia de fibonacci naive es T(n) = T(n-2) + T(n-1) cuya solución es ¡la secuencia de fibonacci!)

De la misma forma, cuando crean una función de hash, esta debería depender de valores de nodos que ya visitaron de alguna manera (ya que contienen información en sus nodos). De la misma manera como cuando se calcula fibonacci(105) usando fibonacci(99) y fibonacci(100) en la versión eficiente, se espera que al implementar la función de hash incorporen los valores de hash calculado anteriormente en el cálculo en vez de revisar todos los nodos previos, pese a haberlos visitado anteriormente. 

TLDR: Con tal de que sea incremental está bien.

**Comment by cahinostroza** [comment]
@kylevon entonces si mi función de hash para un árbol no tiene relación alguna con los hijos de la raíz, no sería incremental?

**Comment by cahinostroza** [comment]
@kylevon puedo utilizar una función no incremental y optar a un descuento? si es así, el descuento sería sólo en el diseño? cada punto de los cuatro de la parte de diseño valen lo mismo?

**Comment by kylevon** [comment]
Cuando dices "Hijos de la raíz" me confunde un poco, porque esta información es crucial para lograr la uniformidad del hash, pero si logras de algún modo hacer un hashing uniforme que logre no usar la información de los hijos de la raíz, entonces no necesitaría un método incremental ya que el hasheo asumo que sería O(1).

No sé aun cómo asignaremos los puntajes del informe. Pero no hay "descuentos", sino que no obtendrías el puntaje correspondiente a ese punto en el INFORME, en cuanto sepa esa información comentaré aquí. En el código, la nota es correspondiente a cuántos tests logras pasar en el servidor y no necesitas implementar el hasheo que planteaste en el informe en el código, eso se puede ver en el enunciado donde dice:

> Deberás escribir un documento de diseño simple donde expliques **cómo resolver el problema usando hashing**. Se recomienda fuertemente escribir este informe antes de escribir el código en C.

Por lo que puedes tener 100% en el informe y 0% en el código y vice versa. 

Eso si, te recomiendo fuertemente que busques una manera de lograr hacer el hashing incremental, porque es muy probable que no logres correr todos los tests en el servidor sin usar hashing incremental y además obtendrías más puntaje en el informe :)

**Comment by kylevon** [comment]
Te recomiendo analizar la complejidad de hashear todos los elementos que quieras hashear en el problema. Esto es lo que intentas minimizar usando el método incremental.
