### ISSUE TITLE
[Tarea 2] Cantidad de nodos

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#127]
Hola! con respecto a la cantidad de nodos, puedo asumir que
a) serán solo de los valores presentes en los tests?
b) no serán mayor a la de Lunatic?

**Comment by kylevon** [comment]
No puedes asumir a)
Pero puedes asumir que la cantidad de nodos para los tests evaluados no son mayores a los de Lunatic. No puedes asumir nada acerca de los tamaños de los tests que se usarán para la competencia de cuál código corre más rápido.

**Comment by kylevon** [comment]
Lo siento, sí puedes asumir que la máxima cantidad de nodos para los tests de la competencia va a ser 2147483647.

**Comment by cahinostroza** [comment]
@kylevon puedo asumir que para cada archivo input la cantidad de nodos de cada consulta será igual o menor a la cantidad de nodos del árbol con que construí el diccionario?

**Comment by kylevon** [comment]
Lo siento por responder tan tarde! No puedes asumir eso, pero no debería ser difícil de distinguir ese caso.
