### ISSUE TITLE
[Tarea 2] Validez de distintas tablas de hash

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#128]
Se puede usar mas de una tabla de hash para la tarea, y que no necesariamente una tabla contenga todo?

**Comment by kylevon** [comment]
Están en libertad absoluta en cómo crean el código de la tarea, con tal de que sea código en C y respete el formate de input/output. 

Con respecto al informe, con tal de que sigas los puntos esperados cualquier decisión que hagan está permitida. Eso si, para cada tabla y función de hash distinta que hagan analiza los puntos explicados en la tarea.

Por si acaso, se puede lograr la tarea sin usar múltiples tablas de hash.
