### ISSUE TITLE
[Tarea 2] Relación entre Hash y arbol

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2133-PUC/2020-2#129]
Tu duda acerca de la T1 acá.
Hola, no entiendo como tiene sentido implementar un hash a un conjunto de datos que ya están ordenados en una estructura, sería como mucho más fácil dejar un heap con 0's y 1's (que ya viene prácticamente dado) para encontrar coincidencias. ¿Cómo tiene sentido integrar un hash en estos datos ordenados? (Incluso podría hacer un hash que solo fuera un array con los datos y la función hashing sea h(n) = n, pero no creo que tenga sentido por que los hash no estarían aportando nada). Eso, gracias.

**Comment by fnberrios** [comment]
Me pasa igual.

**Comment by vichoeq** [comment]
Hola, de eso se trata la tarea. 

¿Ya pensaste la complejidad de resolver el problema usando el árbol que les damos (el cual no es un heap) sin ninguna otra estructura?

¿Dirías que es eficiente?

**Comment by vichoeq** [comment]
Por cierto, parece haber una confusión aca... los datos con los que tu tienes que trabajar no estan "estructurados" en un árbol. Los datos con los que tu tienes que trabajar SON los árboles.

**Comment by Aloncarrasco** [comment]
> Hola, de eso se trata la tarea.
> 
> ¿Ya pensaste la complejidad de resolver el problema usando el árbol que les damos (el cual no es un heap) sin ninguna otra estructura?
> 
> ¿Dirías que es eficiente?

Por ahora me imagino que es n*s (n la cantidad de nodos del arbol y s la cantidad de nodos del arbol t). mmmmm, por ahora lo que se me ocurre es hacer una tabla enorme que contenga todos los arboles posibles del arbol grande, ¿tiene sentido algo asi? ¿o aún no estoy entendiendo?

**Comment by fnberrios** [comment]
Hola Vicho! Es más sencilla la implementación con los hash por mucho. Yo por lo menos no me refiero a que usar hash sea poco eficiente o poco conveniente sino que la función de hash seria trivial ya que puedo utilizar los índices de cada elemento en el árbol que recibo como key (que supongo que vienen ordenas por ID) y al mismo tiempo usarlo como índice del arreglo (h(n) = n que era lo que proponía @Aloncarrasco). Entonces, en ese caso que me pidan encontrar una función de hash suena redundante.

**Comment by Aloncarrasco** [comment]
> Hola Vicho! Es más sencilla la implementación con los hash por mucho. Yo por lo menos no me refiero a que usar hash sea poco eficiente o poco conveniente sino que la función de hash seria trivial ya que puedo utilizar los índices de cada elemento en el árbol que recibo como key (que supongo que vienen ordenas por ID) y al mismo tiempo usarlo como índice del arreglo (h(n) = n que era lo que proponía @Aloncarrasco). Entonces, en ese caso que me pidan encontrar una función de hash suena redundante. Más que redundante me produce desconfianza ya que seria una implementación muy sencilla, entonces no sé si entendí mal el problema o eso es correcto.
Por lo que le entendí, es que si haces eso, después buscar sería mega ineficiente, entonces que rebuscarsela más para hacer esta tabla de hashing

**Comment by vichoeq** [comment]
@Aloncarrasco te falta considerar el número de consultas N. ¿Qué sucede cuando s = n?

@fnberrios la función de hash no debería ser muy complicada... lo que sí, tienes que asegurarte de que entregue el mismo valor para dos árboles iguales, en posiciones distintas, o sino nisiquiera podríamos llamarla una función de hash. En el caso que dices, dos árboles iguales en posiciones distintas dan hashes distintos ya que el hash depende de su posicion 🤔

**Comment by fnberrios** [comment]
Gracias @vichoeq  creo que comprendí!

**Comment by tomasalvarez13** [comment]
> Hola Vicho! Es más sencilla la implementación con los hash por mucho. Yo por lo menos no me refiero a que usar hash sea poco eficiente o poco conveniente sino que la función de hash seria trivial ya que puedo utilizar los índices de cada elemento en el árbol que recibo como key (que supongo que vienen ordenas por ID) y al mismo tiempo usarlo como índice del arreglo (h(n) = n que era lo que proponía @Aloncarrasco). Entonces, en ese caso que me pidan encontrar una función de hash suena redundante. Más que redundante me produce desconfianza ya que seria una implementación muy sencilla, entonces no sé si entendí mal el problema o eso es correcto.
Por lo que le entendí, es que si haces eso, después buscar sería mega ineficiente, entonces que rebuscarsela más para hacer esta tabla de hashing

@vichoeq , sigo con esta duda, entiendo lo que dijiste de que esa funcion entregaria hashes distintos, pero sigo sin ver como usar hashing mejoraria el rendimiento, porque pienso que al hashear, al final voy a obtener lo mismo que ya tenia antes. Tampoco entiendo bien lo del diciconario. Acaso se refiere a una especie de array con los 0 y 1 que nos entregan?? gracias desde ya

**Comment by vichoeq** [comment]
Hola tomás, recuerda la definición general de diccionario: asocia una _key_ a un _value_. Tanto la key como value pueden ser cualquier cosa (un numero, texto, un archivo, una estructura de datos, etc).

La pregunta que se hace en el documento de diseño es como aplicar diccionarios para este problema, sin considerar como están implementados por detras (árboles de búsqueda, tablas de hash, etc). Hashing no es lo que mejora el rendimiento: es el diccionario.

Una vez que tengas claro eso puedes preguntarte como hacer ese diccionario como una tabla de hash, y para eso verás que necesitas hashear los árboles.

Cualquier duda me dices.
Saludos, 
Vicho
