### ISSUE TITLE
[Tarea 2] Función de Hash

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#130]
Hola! Me gustaría saber si, con la solicitud que hacen en la imagen adjunta, nos están pidiendo que al diseñar el hash las keys tengan que ser un árbol estructurado o pueden ser solo los datos? De ser así, también piden que los values del hash sean árboles?
Gracias de antemano.
![image](https://user-images.githubusercontent.com/34272957/95800379-8be80600-0ccd-11eb-8b28-0cf864a65b09.png)

**Comment by vichoeq** [comment]
El árbol SON los datos. En clases definimos una funcion de hash como una funcion que va de un dominio arbitrario D a los números naturales.

Espero que eso responda tu pregunta.

**Comment by fnberrios** [comment]
Estos datos conformarían el dominio D no?

**Comment by vichoeq** [comment]
El dominio serían todos los árboles posibles que siguen las reglas que definimos.

Es decir

* Binarios
* Completos
* Cuyos nodos son blancos o negros
* Con una altura positiva, mayor a 0

**Comment by fnberrios** [comment]
De acuerdo, gracias!

**Comment by jcechavarri** [comment]
@vichoeq Hola! En el caso para que sea incremental es necesario que el nuevo hash a calcular difiera en un dato? Como en el caso de rolling hash? O podemos hacer que por ejemplo tengo un árbol 1100111, siguiendo la lógica del input de la tarea, y para calcular el hash de 110 utilizo el hash de los hijos 1 y 0 ya calculado antes? No se si se entiende.

**Comment by fivaldivia** [comment]
@vichoeq Hola! En el caso para que sea incremental es necesario que el nuevo hash a calcular difiera en un dato? Como en el caso de rolling hash? O podemos hacer que por ejemplo tengo un árbol 1100111, siguiendo la lógica del input de la tarea, y para calcular el hash de 110 utilizo el hash de los hijos 1 y 0 ya calculado antes? No se si se entiende.

**Comment by vichoeq** [comment]
@fivaldivia Para que sea incremental lo importante es aprovechar un hash que ya fue calculado. No tiene por que diferir en un solo dato, pero mientras mas traslape haya entre los datos más eficiente podría ser el cálculo del hash.

Si, el ultimo nivel está lleno. Por eso definimos árbol completo en el enunciado y especificamos cuantos nodos debía tener.

**Comment by Zetaku1** [comment]
@vichoeq Hola como recomiendas analizar la distribución de la funcion de Hash? Pregunto esto debido a que esta parte se hace en el documento de diseño, entonces si quisiera realizar la distribucion, primero tendria que hashear los datos, y para esto debería implementar en C el hasheo de los datos incremental o hay otra manera de ver la distribucion mas simple?

**Comment by yerkko** [comment]
Puedes generar árboles de prueba y analizar el resultado que te da tu función. Puedes hacer esto en otro lenguaje/herramienta que te acomode

**Comment by vichoeq** [comment]
O tambien puedes hacer un análisis teórico (pero no esperamos eso)

**Comment by Zetaku1** [comment]
Gracias!

**Comment by tomasalvarez13** [comment]
Alguna ayuda para poder definir la funcion de hash? Tengo todo super claro, solo que no se me  ocurre muy bien como definirla

**Comment by vichoeq** [comment]
@tomasalvarez13 Hola, a que te refieres con definir?

**Comment by tomasalvarez13** [comment]
@vichoeq Me refiero a determinar que función de hash debo utilizar

**Comment by vichoeq** [comment]
@tomasalvarez13 tu mismo debes diseñar la función de hash. Recomiendo partir de alguna de las funciones de hash que vimos en clases que cumplan las propiedades solicitadas y adaptarla para que funcione con árboles.

**Comment by tomasalvarez13** [comment]
@vichoeq Perfecto gracias!
