### ISSUE TITLE
[Tarea 2] Parámetros de la tabla de Hash

### ISSUE THREAD

**Issue by dasotosilva19** [IIC2133-PUC/2020-2#131]
Hola, tengo una consulta con respecto a los parámetros que se nos pide justificar en el informe que no estoy entendiendo mucho.
A qué se refieren los parámetros de resize y probing ?? Cuando nos dicen "entre otros parámetros", que otros parámetros relevantes debiesemos considerar ??

Otra duda con respecto a la búsqueda en la tabla en una consulta en particular. Se supone que eventualmente el árbol "t" buscado puede aparecer más de una vez dentro de todos los posibles subárboles que podemos formar con el árbol grande que nos dan como input. Pero se supone que al buscar el indice de hash del subárbol "t", eventualmente encontraremos en la tabla el árbol "t", pero como seguimos buscando si ya tuvimos un éxito en la búsqueda ?? debemos seguir iterando en la tabla (hasta que punto)?? todos los subárboles iguales pero en distintas posiciones debiesen estar cercanos en la tabla o estarían en la misma posición?? Me confunde un poco el buscar más subárboles que sean iguales al árbol "t" de la consulta ya habiendo encontrado el primero.

**Comment by vichoeq** [comment]
Recuerda que la tabla debe modificar su tamaño (resize / rehashing) según su factor de carga. Ese es un parámetro.

Probing = Sondeo; si usas direccionamiento abierto, cual es tu estrategia para buscar la "siguiente celda disponible"

Respecto a tu segunda pregunta... tienes que pensar bien cual va a ser tu **_key_** y cual el **_value_** que le asocias en el diccionario. Me dices que estás guardando "t"... esa es la _**key**_ o el **_value_**? Recuerda en el documento de diseño que debes explicar como usar diccionarios para este problema. No te tires a hacer la tabla de hash sin tener bien claro eso.
