### ISSUE TITLE
[Tarea 2] Árboles que no están

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2133-PUC/2020-2#132]
Además de ser pregunta de T2 también es pregunta de materia. Segun lo que entiendo (por lo que vimos en clases), la tabla de hash existe antes de las consultas mismas, de modo que al hacer las consultas simplemente se revisa. Pero entonces, ¿esto significa que todos los posibles subárboles (y aquí entran todas las combinaciones distintas de los colores de los nodos, además de la altura) del árbol Sigma tienen que estar en la tabla de hash a priori, antes de la consulta? 
Me hace ruido eso, porque siento que demoraría mucho, por eso pregunto...

(O sea, hasta ahora entiendo que lo que se busca es un nodo que tiene un ID, y que de la hashfunction obtenemos el índice de la tabla ya hecha, y en ese índice está el ID o los IDs de los nodos que cumplen (o un puntero, etc). Y que a la vez este ID podría estar en otras partes de la tabla, porque puede hacer referencia a dos subarboles distintos en consultas distintas.)

**Comment by vichoeq** [comment]
Cuando uno hace una busqueda en un diccionario, perfectamente el dato puede no estar y la consulta debería retornar eso (un NULL, por ejemplo). Asi que te pregunto yo a tí si es necesario guardar sub-arboles que no existen en nuestros datos solo para poder cubrir el caso en el que los quieran consultar.

Lo último que dices es completamente cierto :) Por lo mismo, lo que deberías guardar en la tabla es el par (id, altura). Ese par sí debería ser único.

**Comment by sopadeoliva** [comment]
gracias, ya entendí ahora :) Entonces se podría encontrar una cota superior de subárboles distintos dentro de Sigma y a partir de eso ver el tamaño de la tabla de hash?

**Comment by vichoeq** [comment]
O puedes ir llenando la tabla y hacer rehash cuando esta muy llena, como explicamos en clases.
