### ISSUE TITLE
Importancia Incrementalidad [Tarea 2]

### ISSUE THREAD

**Issue by hsazos** [IIC2133-PUC/2020-2#133]
Hola! 

Es duda de la materia mas que nada. No entiendo muy bien el concepto de incrementalidad. Si mi tabla de hash funciona como diccionario y solo tengo que tener mi llave para acceder a mi valor, ¿Qué importancia tiene que  mi función sea incremental? Lo único que se me ocurre es que la función de hash de un valor muy alto sea muy difícil de computar ¿Pero eso no quebraría la ventaja del hashing?

**Comment by yerkko** [comment]
Hello, creo que estás un poco confundido entre el proceso de *hashear* datos y el usar la tabla de hash para acceder a este valor. Cuando se habla de incrementalidad nos referimos a la función misma, al proceso de convertir los datos a números. Imagina que tienes un tablero de ajedrez/juego de mesa que se debe hashear. Será eficiente recalcular el hash del tablero entero de 8x8 cuando sólo una pieza se movió? En ese contexto, una función de hash incremental revisaría "las diferencias" entre ambos estados y recalcularía incrementalmente sólo con esas diferencias la nueva función. De esta manera, obtener el nuevo valor del hash es sólo O(1), en vez de O(número de celdas del tablero).

Esto es completamente ajeno al concepto de tabla de hash/diccionario/hashmap, la cual sólo tomaría este valor y lo indexaría para fácil acceso

**Comment by hsazos** [comment]
Efectivamente, estoy confundido. Pero si el árbol que me entregan no cambia, y si cambia es pq inicie otra instancia del programa ¿Mi función igualmente debe estar diseñada para enfrentar cambios de inserción o deleción(no se como se escribe) en el árbol original?

**Comment by kylevon** [comment]
El árbol original no cambia. Solo se hacen consultas.

**Comment by kylevon** [comment]
Por lo que no creo que necesites soportar la inserción o eliminación

**Comment by hsazos** [comment]
Creo que entendí.  Entonces si yo quiero por ejemplo hashear recursivamente todos los subarboles posibles de mi árbol, partiendo desde el nodo raíz, si hasheo mi (1)nodo raíz y sus hijos directos, y luego el (2)nodo raíz, con sus hijos directos y los hijos directos de los hijos. Mi función incremental debería usar el árbol (1) para hacer mas eficiente calcular el hash del árbol (2)?

**Comment by yerkko** [comment]
@hsazos Tuve que eliminar tu comentario porque es tarea individual entender cómo implementar esto :(

**Comment by hsazos** [comment]
@yerkko  ahh yaya, comprendo. Gracias por la ayuda igual, me ayudó a entender :)

**Comment by Juan379** [comment]
La idea es que sea incremental va de la mano de que un árbol de 3 nodos y uno de 7 nodos pueden compartir los mismos 3 nodos iniciales? Entonces, al tener el hash del arbol de 3 nodos, bastaria con ver los 4 nodos nuevos para hashear el de 7, en vez de hashear de cero este último?

**Comment by vichoeq** [comment]
@Juan379 Por ejemplo :) Un árbol de 7 nodos tiene 3 sub-árboles de 3 nodos \*wink wink\*

**Comment by Juan379** [comment]
@vichoeq En ese caso, el hecho de que sea incremental beneficaría si por ejemplo ya calcule el hash de alguno de esos 3 subárboles, entonces para calcular el árbol grande ya tengo como un _"headstart"_?

**Comment by vichoeq** [comment]
@Juan379 de eso precisamente se trata el hash incremental :) Mientras más tengas precalculado, más "_headstart_" tienes, asique más eficiente es tu hash.

Por eso el enunciado recomendaba formularlo segun los hashes de los hijos, así tienes el hash de 2 subárboles que no tienen elementos en comun, y solo te falta agregar un elemento al hash: la raíz.

Pero partir del mismo árbol con uno menos de altura, y agregar las hojas, tambien es un enfoque incremental válido.

**Comment by Aloncarrasco** [comment]
> @Juan379 de eso precisamente se trata el hash incremental :) Mientras más tengas precalculado, más "_headstart_" tienes, asique más eficiente es tu hash.
> 
> Por eso el enunciado recomendaba formularlo segun los hashes de los hijos, así tienes el hash de 2 subárboles que no tienen elementos en comun, y solo te falta agregar un elemento al hash: la raíz.
> 
> Pero partir del mismo árbol con uno menos de altura, y agregar las hojas, tambien es un enfoque incremental válido.

Pero entonces tengo que ir reconstruyendo el hash a medida que hago consultas?
O lo construyo todo al principio, pero de forma incremental?

**Comment by vichoeq** [comment]
> O lo construyo todo al principio, pero de forma incremental?

this :)

Para los árboles que tienes que consultar, inevitablemente vas a tener que calcularles todo el hash. Pero los que son sub-arbol del arbol SIGMA, entonces sabes que muchos sub-árboles contienen a otros sub-arboles que tambien vas a tener que incluir en la tabla = tambien vas a tener que hashearlos.
