### ISSUE TITLE
[Administrativo]  Repo T2

### ISSUE THREAD

**Issue by narierao** [IIC2133-PUC/2020-2#135]
Hola! todavía no me ha llegado el correo para aceptar el repositorio de la T2. Quería saber si esto era algo que a todos les pasa o sólo a mi. 

Saludos!

**Comment by caespinoza5** [comment]
¡Hola!

Citando al anuncio de la Tarea 0 (y que aplica a todas las tareas), no necesariamente les llegará una invitación al repositorio al correo, pero si tendran acceso a él y estará disponible desde el momento en que se anunció que lo estaría. En particular para esta tarea el mismo 7 de octubre fueron creados los repositorios.

Acabo de reenviarte la invitación: Ahora deberías poder acceder nuevamente. Si tienes cualquier problema de acceso me avisas porfavor.

Saludos,
Cristóbal

**Comment by narierao** [comment]
Muchas gracias! te pasaste :D
