### ISSUE TITLE
Direccionamiento abierto [Tarea 2]

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2133-PUC/2020-2#138]
Hola, no me quedó muy claro que se hace cuando no encuentro lo que queria encontrar en un índice determinado, porque segun lo que entendí debería revisar hacia la derecha por la tabla, entonces por ejemplo si estoy buscando en el índice cero y en esa posicion no esta lo que estaba buscando, tendría que recorrer toda la tabla, lo que me suena muy costoso. 
Muchas gracias.

**Comment by baaldana** [comment]
Hola, tengo la misma duda. Podría algún ayudante responder por favor?

**Comment by yerkko** [comment]
Hola, esto se vio en clases. En efecto, en el peor caso tienes que buscar en toda la tabla. Es una de las consecuencias de tener una mala función de hashing que distribuye no-uniforme.
