### ISSUE TITLE
Uniformidad función de Hash[Tarea 2]

### ISSUE THREAD

**Issue by jalliende** [IIC2133-PUC/2020-2#139]
Que "tan uniforme" debe ser la función de hash? Que me pasa que para unos valores en particular la función como que explota (son muy pocos) pero para el resto si es bastante uniforme.

**Comment by yerkko** [comment]
Debido a que el curso no es de estadística, no es necesaria una métrica concreta de uniformidad. Sólo basta con que justifiques que los resultados de la función son "lo suficientemente uniformes", lo que de todas formas se verá reflejado en los resultados empíricos.

Si tienes curiosidad acerca de qué métodos se pueden usar (completamente opcional en el contexto de la tarea), puedes revisar los tests de hipótesis de fit de distribución kolmogorov-smirnov o anderson-darling.
