### ISSUE TITLE
[Tarea 2] Formato Output

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#142]
Hola! ¿Es necesario que mi output presente los ids de menor a mayor? Por ejemplo, 2 4 7. O ¿podría presentarlos en otro orden, por ejemplo 4 2 7?

**Comment by caespinoza5** [comment]
¡Hola!

Sí, es necesario que estén de menor a mayor.

**Comment by fnberrios** [comment]
Gracias! @caespinoza5

**Comment by fnberrios** [comment]
En los test hay una línea al final, en los outputs de mi programa también debe estar contenido ese espacio?
