### ISSUE TITLE
[Tarea 2] Duda enunciado sobre uniformidad de la funcion hash

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2133-PUC/2020-2#143]
Hola!

Se nos pide que el todo el proceso de hash sea uniforme o que la funcion de hash en si debe serlo (Se que esto esta medio explicito en el enunciado, pero quizas fue una condicion).

Cual seria el problema que mi funcion de hash no sea uniforme pero luego con la funcion de ajuste esta si quede uniforme? Basicamente, corregir la uniformidad con el metodo multiplicativo (Como vimos en clases).

Muchas gracias

**Comment by kylevon** [comment]
Si tu función de hash no es uniforme pero luego con el ajuste se corrigen las irregularidades para que la distribución final en las posiciones de la tabla de hash sean uniformes para cualquier tamaño, entonces estaría bien.

**Comment by Alonsinho1** [comment]
muchas gracias!

**Comment by tomasalvarez13** [comment]
Pero para efectos del documento de diseño esta funcion de hash no seria valida o no? Porque el enunciado dice que debe ser uniforme. Si no fuese valida, seria valido hacer este ajuste dentro de la funcion de hash?

**Comment by tomasalvarez13** [comment]
@vichoeq Perfecto, pero que pasa si dentro de mi funcion de hash le sumo o multiplico algo por ejemplo para que quede uniforme? Es valido?

**Comment by vichoeq** [comment]
@tomasalvarez13 no importa lo que hagas adentro mientras el output distribuya uniforme. La unica restriccion es que debe depender 100% del árbol que estás hasheando (y 0% de la tabla o su largo m)

**Comment by tomasalvarez13** [comment]
@vichoeq Dale gracias!!
