### ISSUE TITLE
[Tarea 2] Duda recorrer árbol inicial 

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2133-PUC/2020-2#145]
Vi la sesión de ayuda y el resto de las issues pero todavía no me queda claro una cosa.
Tengo entendido que cada sub-árbol entregado será hasheado, y luego se buscara en la hast table para hacer las respectivas modificaciones. La duda que tengo es:
- ¿En qué momento recorro el árbol inicial para hacer la verificación de si el sub-árbol esta o no en el árbol original?
- ¿La idea es comparar hashes? ¿De ser así, tengo que sacar el hash de cada sub-árbol del árbol inicial?
- ¿Si no recorro nodo por nodo, cómo se el índice del nodo a insertar?

Me quedo super claro el resto, pero todavía no logro entender qué hacer y cuándo con el árbol inicial.
Muchas gracias.

**Comment by kylevon** [comment]
Primero, hay muchas formas de resolver este problema. La idea es que ustedes averigüen cómo resolverlo por sus cuentas. Por eso mismo, la primera pregunta no la puedo responder porque depende de cómo aborden el problema.

En el segundo punto estás en lo correcto, la idea es comparar el hash antes de comparar los árboles. Esa es la forma que las tablas de hash obtienen su eficiencia. Y claro, si están consultando por un sub árbol de altura x, es necesario haber revisado de ante mano todos los sub árboles de altura x. Y la idea de la tabla de hash es poder almacenar el resultado de estas consultas para no tener que revisar nodo por nodo nuevamente.

En el tercer punto, no entiendo por qué no recorrerías nodo por nodo en algún momento de ejecución de tu árbol. ¿En alguna parte de la sesión de ayuda/ issues dijimos algo que apunte a eso? Es necesario haber revisado todos los nodos del árbol donde puede haber un sub árbol de altura x en algún momento de la ejecución de tu programa para saber si en ese índice está el sub árbol. 

En esas respuestas traté de que no se excluyeran soluciones posibles a la tarea, en específico porque buscamos darles libertad para que usen creatividad para resolver el problema.

**Comment by Ignaciomendezp** [comment]
Muchas gracias!
