### ISSUE TITLE
[Tarea 2] Hash iguales

### ISSUE THREAD

**Issue by emena97** [IIC2133-PUC/2020-2#146]
Hola! 
Si tengo una función de hash que me da el mismo hash para 2 sub-arboles que son distintos, esto esta necesariamente malo?
O puedo revisar en el árbol original a todos los sub-arboles con ese hash para ver si efectivamente son iguales al que me piden?

Al final la duda es si dos arboles distintos pueden tener el mismo valor de hash? o eso hace que la función este mala?

La otra duda que tenía es que cuantos hash distintos se supone que uno debiera tener para un arbol de X nodos?

Muchas Gracias

**Comment by kylevon** [comment]
Es esperable que múltiples árboles tengan el mismo hash. Para mostrarte por qué, veamos el caso hipotético de todos los árboles de altura 15.

Todos los árboles posibles de altura 15 son 2^(2^15 - 1). Si creamos un hash específicamente para árboles de altura 15 que no pueden tener colisiones, entonces necesitarías un objeto de 32767 bits (2^15 - 1) para representarlo. 

Luego, nota que los unsigned long tienen solo 64 bits. Entonces si deseas que se cumpla esa propiedad tendrías que encontrar o crear una estructura de datos en C que permita manejar datos con (2^h + ..2^2 + 2 - h) cantidad de bits para un árbol original de altura h para poder representar todos los posibles árboles de altura 1 a altura h.  Espero que se entienda que esto es impráctico. 

En la práctica se revisa primero el hash, y luego de alguna manera revisar si los dos árboles son iguales para ver la igualdad en una tabla de hash.

La cantidad de hashs distintos que uno espera tener para un árbol de X nodos depende del tamaño de la estructura de datos que uses para representar el hash. Si eliges un hash de tamaño n por ejemplo sería 

min(2^n, 2^h + ... + 2^2 - h)
