### ISSUE TITLE
[Tarea 2] Duda uso memoria

### ISSUE THREAD

**Issue by bpardobravo** [IIC2133-PUC/2020-2#148]
Hola, creo que después de ver todas las issues y clases sigo teniendo una duda fundamental.
Si tengo que poblar la hash table con todos los subárboles posibles del árbol grande (o mejor dicho, su representación, por ejemplo: (ID, altura) ), eso significa guardar muchísimas representaciones de sub árboles en la hash table, independiente de la cantidad de índices distintos en ésta. (habría que guardar cada sub árbol de altura 1, cada subárbol de altura 2, 3, ...etc)
¿Cómo es que se supone que el método de hash tables evita el uso excesivo de memoria?

**Comment by dvogaz** [comment]
Tengo la misma duda, o es que solo se realiza la búsqueda con la función de hash sin almacenar nada en memoria?

**Comment by vichoeq** [comment]
@bpardobravo No es necesario guardar cada tupla, puedes guardar solo las tuplas que representan árboles distintos. La cantidad de árboles distintos es acotada, así que no deberías usar mucha memoria. Si bien la cantidad exacta de árboles distintos es complicada, deberías poder facilmente calcular su cota superior.

@dvogaz no, efectivamente estamos almacenando cosas en memoria. De eso no hay escapatoria para este problema.

**Comment by bpardobravo** [comment]
Mmm pero si me hacen una consulta para un árbol particular que, por ejemplo, es de altura 4 y está repetido 8 veces en el árbol grande, necesito saber todos los índices en donde se encontraba ese árbol particular en el grande o no? 
Cómo hago eso si solo guardé 1 posición en la cual se encontraba, y las otras no las guardé porque no eran árboles distintos?

**Comment by dvogaz** [comment]
@bpardobravo Quizás se podrían guardar un arreglo con los id's de las raíces de los árboles, ya que es lo único que hay retornar, no el árbol completo
