### ISSUE TITLE
[Duda C] Error al compliar T0

### ISSUE THREAD

**Issue by matiuc** [IIC2133-PUC/2020-2#15]
[Plataforma de C] = Ubuntu 18.04

Al compilar el programa me sale lo siguiente:

compiled 'obj/simulate/mould.o'
compiled 'obj/simulate/main.o'
compiled 'obj/simulate/cell.o'
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
Makefile:119: recipe for target 'simulate' failed
make: *** [simulate] Error 1

Y no se a que puede deberse ya que en internet no sale nada parecido :(.

**Comment by caespinoza5** [comment]
¿Revisaste [esta guía](https://github.com/IIC2133-PUC/2020-2/blob/master/Gu%C3%ADas/Setup/3.0%20GTK.md) y [esta issue](https://github.com/IIC2133-PUC/2020-2/issues/11)?

**Comment by matiuc** [comment]
Me funcionó. muchas gracias :+1:
