### ISSUE TITLE
[Tarea 2] Uniformidad función de hash

### ISSUE THREAD

**Issue by emena97** [IIC2133-PUC/2020-2#151]
Hola! Con respecto a la uniformidad, es estrictamente necesario que sea uniforme para tener el puntaje completo?
o eso se deja a criterio y basta con analizar su uniformidad?

Muchas Gracias

**Comment by vichoeq** [comment]
El enunciado lo separa en dos puntos. Si tu funcion no es uniforme aun puedes tener el puntaje por el análisis, pero no vas a tener el puntaje de ser uniforme.

**Comment by tomasalvarez13** [comment]
Para demostrar uniformidad, es suficiente mostrar un grafico de los hashes de todos los subarboles de un arbol de 63 nodos? O es necesario más?

**Comment by yerkko** [comment]
Es parte del proceso de ingeniería/científico determinar la cantidad de datos así como la metodología y recursos para demostrar tu hipótesis, quedan a tu criterio esos detalles.
