### ISSUE TITLE
No guardar subárboles de tamaño 1 [Tarea 2] 

### ISSUE THREAD

**Issue by vWing7** [IIC2133-PUC/2020-2#152]
Hola, ya que no se harán consultas por subárboles de tamaño 1, ¿se puede no almacenar estos en la tabla de hash?, en caso de ser así, ¿se puede asumir esto mismo en el análisis de uniformidad?

Gracias

**Comment by kylevon** [comment]
Sí a todas las anteriores :) Éxito!
