### ISSUE TITLE
[Tarea 2] Hash incremental

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2133-PUC/2020-2#153]
Hola! 
En otra ocasión pregunté si el hash incremental podía ser partiendo de la raiz hacia abajo o desde las hojas hacia arriba y me respondieron que ambos eran posibles. Estoy un poco confundida con esto.
El ejemplo de incremental que vimos como el del ADN sería en este caso partiendo de las hojas hacía arriba o no? Por ejemplo: hash de un hijo = 1, hash del otro hijo =1: hash del padre= 1+1=2. Ahi me hace sentido lo de "incremental"

Por otro lado, si se parte de la raiz y se sigue con los hijos no le encuentro el sentido a lo de incremental.
Por ejemplo: hash raiz = 2, hash izquierdo: 2+1=3, hash derecho: 2+2=4. Acá, se esta sacando el hash de los hijos a partir del padre, pero ¿cuenta esto como incremental? Al final no se está aprovechando el calculo de un hash para otro, sino que igual hay que calcular todo.
Pregunto por que encontré mas fácil hacer algo del tipo 2, pero a la hora de mostrar/entender que estoy haciendo algo incremental me compliqué.

Estoy entendiendo algo mal? O efectivamente eso no es incremental?

Gracias!

**Comment by kylevon** [comment]
Hmm, efectivamente la forma que pensaste en incorporar las hojas en tu caso no parece ser incremental. Se pueden de ambas formas, pero me cuesta mucho mostrarte por qué es así sin explicarte la solución. Eso si, voy a dar un hint para esa forma de incrementalidad, mira en "niveles" en vez de padres e hijos. Espero no haber dicho mucho con eso 🤭. De todas formas, reitero que hay muchas maneras de solucionar el problema, y si llegan a hacerlo incremental podrían calcular que la complejidad asintótica es menor que en el caso no incremental.

**Comment by kmhaller** [comment]
Hola, en el informe se pide que se explique un hash incremental desde las hojas. Se puede explicar
el hash incremental desde la raiz?

**Comment by yerkko** [comment]
Yes, puedes explicarlo de la forma que encuentres mejor, mientras sea incremental y sea correcto.
