### ISSUE TITLE
[Tarea 2] Outputs incorrectos en el server

### ISSUE THREAD

**Issue by patogramador** [IIC2133-PUC/2020-2#155]
Hola, estuve probando mi tarea y en el servidor me tira 2 de los 12 tests malos. La cosa es que probe corriendo esos tests desde mi pc y compare esos outputs con los que nos entregan mediante el comando que nos dieron para la tarea 0.

diff --strip-trailing-cr out.txt Normal/solutions/test6.txt

Con este comando no me sale ninguna diferencia entre los dos archivos, hay alguna razon por la cual me puede estar tirando WRONG OUTPUT en el servidor?

**Comment by caespinoza5** [comment]
¡Hola!

Revisa cuánta memoria estás ocupando para esos tests. Puede ser que el servidor te tire WRONG OUTPUT porque ocupaste más de 1.5gb de memoria. Esto lo puedes revisar con valgrind.

**Comment by patogramador** [comment]
Ok gracias!
