### ISSUE TITLE
[Tarea 2] Hash negativo

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2133-PUC/2020-2#156]
Hola!
Por que podría pasar que mi hash a veces sale negativo? Es un int y le hago operaciones XOR y shift
Traté definiendolo como unsigned int, pero no funcionó.

Gracias!

**Comment by agustin-rios** [comment]
Probablemente tu variable sea tipo signed (los cuales toman valores negativos) y tengas un overflow
