### ISSUE TITLE
[Tarea 2] Tips para encontrar error de output.

### ISSUE THREAD

**Issue by szabala** [IIC2133-PUC/2020-2#157]
Hola, dejo esta issue por si alguien tiene un tip para encontrar un error en la implementacion de mi tarea. Esta retorna un output correcto para todos los test Easy que subieron, sin embargo no es el caso para los demas test.  Ademas, como la escala de los test Normal es mucho mayor que la de los test Easy, me es dificil encontrar patrones comunes de error en el output :cry: .

Cualquier consejo se aprecia :sweat_smile:

**Comment by kylevon** [comment]
Podrías crearte algunos tests propios para revisar los casos bordes o ir cambiando los tests easy. También puedes ver las líneas diferentes en los tests Normal y preguntarte si son los árboles pequeños o árboles grandes los que causan problemas. Tal vez no se estén ordenando bien los índices. Tal vez te faltan algunos índices, repites índices, no encuentra el árbol,... Son tests muy grandes pero puedes deducir cosas como esas e ir probando con tests propios.

**Comment by szabala** [comment]
Gracias! Pude encontrar el problema :smile:

**Comment by vichoeq** [comment]
Sumado a lo que sugiere Kyle, quizás el problema es que tu función hash está dando valores distintos para árboles equivalentes; puedes buscar exhaustivamente (es decir, sin usar la tabla) el t que te está fallando y comparar el hash de t con los sub-árboles en Sigma que son iguales a t. 

Si el error no es el hash mismo, quizás estás guardando mal los indices en la tabla. Con la busqueda exhaustiva ya deberias haber encontrado los indices asi que debería ser bien directo revisar que son los mismos que están guardados en la tabla.
