### ISSUE TITLE
[Tarea 2] Función pow()

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2133-PUC/2020-2#162]
Hola tengo el siguiente problema: No entiendo porque me imprime 256, 4 y 1023. Debería imprimir siempre 4 según yo. Además, el piso actual debería aumentar en 1 cada vez que se corre esa linea o no?
![image](https://user-images.githubusercontent.com/42189004/97344349-64657180-1867-11eb-956d-ae1cfce47430.png)

**Comment by benjaurr** [comment]
Yo creo que es porque pow retorna un float, y %d es para imprimir un int. %f es para imprimir floats.

**Comment by Tomas-Ira** [comment]
Gracias, ahí lo solucioné era algo que ver con eso.

**Comment by JJJGGGG** [comment]
Dato:
```c
pow(2, x) == 1<<x;
```
