### ISSUE TITLE
[Tarea 2] [Status: COMPILATION ERROR]

### ISSUE THREAD

**Issue by folozano** [IIC2133-PUC/2020-2#163]
Hola!

Después de horas dedicadas a la tarea, corro los tests en mi computador y no tengo ningún problema - output correcto para todos los tests disponibles - pero al probarlo en el servidor ocurre que su ejecución termina en segundos, y me dice: Status: COMPILATION ERROR.

Al compilar con make en mi computador, no tengo problema alguno. El programa lo corro con ./remember

Ayuda.

**Comment by vichoeq** [comment]
@folozano hola, si aun no has usado tu pase me puedes hablar por interno por discord. Sino, podemos tratar de resolverlo por acá.

**Comment by caespinoza5** [comment]
@folozano ¿Subiste la última versión de tu tarea a github? Recomiendo que también elimines el archivo `consultas[j]`

**Comment by folozano** [comment]
Borré el archivo indicado pero no tuvo efecto, voy a usar el Discord. Muchas gracias por las rápidas respuestas.
