### ISSUE TITLE
[Tarea 3] Nodo sin vecinos | tercera restricción

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#164]
en el juego está presente la siguiente restricción:
![image](https://user-images.githubusercontent.com/48263952/97518594-49cdee00-1976-11eb-894f-5f5d40ee7602.png)
Pese a que del enunciado se tiene  del input que '0' representa que la casilla no posee valor asignado, por lo que de haber un nodo con valor cero, eso también podría significar que no hayan casillas alrededor para el output. (ya que no habrían casillas vacías en el output).

Debido a lo anterior, deseo confirmar si está presente o no esta restricción

**Comment by ifieldhouse** [comment]
La regla no es necesaria, pero puedes considerarla si lo deseas
Como dice el enunciado, debes encontrar *una* solución tal que las restricciones se cumplan

**Comment by juakoke** [comment]
Una duda, en este caso aquella casilla que no ve a nadie, en el input sería un "0" pero un 0 realmente por enunciado es una casilla vacía, es correcto dejarla como 0 de todas formas?

**Comment by ifieldhouse** [comment]
No, ya que otro de los requerimientos es que cada casilla esté pintada
> El objetivo del juego es pintar con el color correcto *cada una* de las celdas vacías [...]

**Comment by Aloncarrasco** [comment]
> No, ya que otro de los requerimientos es que cada casilla esté pintada
> 
> > El objetivo del juego es pintar con el color correcto _cada una_ de las celdas vacías [...]

Entonces las casillas sin vecinos habría que volverlas un -1 de todas formas no?

**Comment by caespinoza5** [comment]
Hola @Aloncarrasco,

Idealmente sí, aunque el servidor debería funcionar de ambas maneras, por lo que te recomiendo que pruebes en el servidor. Lo importante es que si colocas un número N >= 0 en tu output es porque puede ver N círculos azules.
