### ISSUE TITLE
[Tarea 3] Tableros resolvibles mediante técnicas concretas.

### ISSUE THREAD

**Issue by Alonsortega** [IIC2133-PUC/2020-2#166]
En la versión online del juego, una característica de los tableros es que siempre pueden resolverse utilizando técnicas concretas. Me gustaría saber si los tableros de prueba de la tarea también cumplirán con esta característica.

Otra forma de formular mi inquetud sería preguntar si todos los tableros de prueba de la tarea pueden eventualmente ser resueltos sin utilizar backtracking.

**Comment by yerkko** [comment]
Es una tarea de backtracking y por tanto está pensada para ser resuelta usando esa técnica. No podemos asegurarte que tu técnica analítica funcione con los tests. De todas formas, puedes usar el server para corroborar eso por tu cuenta.
