### ISSUE TITLE
[Tarea 3] Especifidad de modelacion "sustenacialmente distinta"

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#167]
Hola!

Deseo saber que tan distinta debe ser la modelación alternativa.
¿Basta con que las variables y el dominio sean distintos?
¿Basta con que las restricciones sean distintos?
¿En caso de no encontrar una sustancialmente distinta, se pueden plantear dos, una que sea con variable/dominio distinto y otra con restricciones distintas?

**Comment by vichoeq** [comment]
Hola, perdona lo tarde: con que las variables sean distintas es suficiente, ya que tanto los dominios y las restricciones se formulan en torno a las variables.
