### ISSUE TITLE
[Tarea 3] Outputs distintos

### ISSUE THREAD

**Issue by MINGOD24** [IIC2133-PUC/2020-2#168]
Hola,

Al imprimir los resultados de mi programa me salen outputs distintos en algunas ocasiones a los de solutions. Revisandolo detalladamente no he sido capaz de encontrar errores, puede ser que hayan multiples soluciones, o estoy mal nomas?

**Comment by yerkko** [comment]
Como dice el enunciado, las soluciones pueden no ser únicas. Por lo mismo, sólo debes comprobar que cumplan las restricciones.

![image](https://user-images.githubusercontent.com/48332955/98326343-c2185d00-1fcf-11eb-8273-ba1db6b0f65b.png)

**Comment by Aloncarrasco** [comment]
> Como dice el enunciado, las soluciones pueden no ser únicas. Por lo mismo, sólo debes comprobar que cumplan las restricciones.
> 
> ![image](https://user-images.githubusercontent.com/48332955/98326343-c2185d00-1fcf-11eb-8273-ba1db6b0f65b.png)

y como verán que es válida?
usarán un programa para eso?

**Comment by caespinoza5** [comment]
@Aloncarrasco así es 🙂 recuerda que puedes probar la tarea en el servidor.
