### ISSUE TITLE
[Tarea 0] Inicio Slime Mould

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#17]
Hola! ¿Se supone que al iniciar la simulación del Slime Mould siempre se comenzará con solo una célula (la germinal) y a partir de esa comenzarán a suceder los Eventos o no?

**Comment by caespinoza5** [comment]
¡Hola!

Sí, siempre comenza solo con la célula germinal.

**Comment by fnberrios** [comment]
@caespinoza5  Gracias!
