### ISSUE TITLE
[Duda enunciado]

### ISSUE THREAD

**Issue by fivaldivia** [IIC2133-PUC/2020-2#170]
Hola! En el enunciado cuando hablan de "escoger una de estas dos modelaciones y proponer para ella dos mejoras" para le informe, se refiere a escoger entre la propuesta por nosotros y la entregada por enunciado? 

Gracias!

**Comment by yerkko** [comment]
sí

**Comment by fivaldivia** [comment]
Ya buenísimo gracias @yerkko. Me surgieron otras dos, cuando se pide presentar otra modelación, simplemente se pide definir las variables, dominio y restricciones de esta nueva modelación? O se espera algo más?
Y sobre las podas y heurísticas, pueden ser las mismas que implementamos en nuestro código cierto?

**Comment by yerkko** [comment]
> Me surgieron otras dos, cuando se pide presentar otra modelación, simplemente se pide definir las variables, dominio y restricciones de esta nueva modelación? O se espera algo más?

Tiene que ser una nueva forma de resolver el problema completamente distinta a la que prupusimos en el enunciado. La idea es que sea 100% autocontenido

> Y sobre las podas y heurísticas, pueden ser las mismas que implementamos en nuestro código cierto?

Yes

**Comment by fivaldivia** [comment]
@yerkko  entiendo que tiene que ser una nueva forma completamente distinta, pero se refiere a definir variables, restricciones y dominio? O se están refiriendo a no usar backtracking y hacer otra cosa?

**Comment by yerkko** [comment]
Ah, sí... Se refiere a variables y restricciones. No es necesario que usen técnicas externas a backtracking
