### ISSUE TITLE
[Tarea 3]: Duda celdas grises

### ISSUE THREAD

**Issue by Franco1605** [IIC2133-PUC/2020-2#171]
Hola, tengo la siguiente duda. Estoy complicado con la modelación de las celdas grises. Si en una misma columna de 4 valores, tengo lo que sigue:
2
0
0
1
el 2 estaría "viendo" al 1 o no?

Muchas gracias de antemano !

**Comment by yerkko** [comment]
En el estado actual, sí. Si pones una celda roja entre los dos, 2 no podría ver a 1
