### ISSUE TITLE
[Tarea 3] Backtracking Generalizado

### ISSUE THREAD

**Issue by hsazos** [IIC2133-PUC/2020-2#174]
Hola!

Según el algoritmo de backtracking que esta en las diapos, las restricciones se designan en un conjunto R. Como en la tarea ya sé las restricciones, no tendría problemas en hardcodearlas verdad? 

saludos

**Comment by hsazos** [comment]
Y otra duda aparte que me quedó, nosotros trabajamos con el visualizer como tablero? o tenemos que crear nuestro propio arreglo para trabajar?

**Comment by dvogaz** [comment]
@hsazos en discord repondieron que había que crear nuestro propio arreglo para trabajar, porque desde main solo puedes cambiar los valores en el visualizador no obtener información. El visualizador es solo apoyo.
Sobre lo primero que preguntaste, tengo la misma duda 😔

**Comment by yerkko** [comment]
@dvogaz tiene razón. Recuerden que aunque C sea un lenguaje de bajo nivel, de todas formas es buena práctica separar frontend de backend.

> no tendría problemas en hardcodearlas verdad?

No entiendo a qué te refieres con esto :(

**Comment by hsazos** [comment]
Gracias @dvogaz !

**Comment by hsazos** [comment]
@yerkko  Me refería a que en el código de backtracking que esta en las diapos había que entregarle las  restricciones como un parámetro de la función. Pero supongo que como nosotros tenemos un problema concreto con restricciones concretas, no es necesario que le pasemos el parámetro, sino que lo implementemos dentro de la función que haga el backtracking. Porfa si me equivoco corrígeme uwu

**Comment by yerkko** [comment]
Ah, sí, no es necesario que la función reciba restricciones como parámetro. Te recomendaría definirlas como variables globales o macros

**Comment by hsazos** [comment]
@yerkko que es macros? Yo pensaba aplicar una función que revisara que se cumplieran las condiciones en el tablero cada vez que pintara algo, esta mal?

**Comment by yerkko** [comment]
No te compliques con lo de las macros, era sólo una sugerencia. Lo que dices está super bien 🐸

(Si quieres saber más de macros, puedes ver este [link](https://www.educba.com/macros-in-c/), pero reitero, era sólo una idea, **no** son corroborar)

**Comment by hsazos** [comment]
@yerkko ahh yaya, gracias!
