### ISSUE TITLE
[Tarea 3] Tests Hard TIMEOUT

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2133-PUC/2020-2#176]
Hola, tengo una confusión respecto a los tests hard. Los corro en el servidor y me tiran TIMEOUT error. Los test easy y normales se me hacen en menos de 0.1s. He optimizado mi función lo más que se me ocurre y no logro alcanzar los tiempos pedidos. Hay alguna consideración especial que deba tener o un consejo que me puedan dar?

![image](https://user-images.githubusercontent.com/42189004/98854556-7a635c80-2439-11eb-84ef-daace5286e06.png)

**Comment by bgfeuereisen** [comment]
x2, ando en las mismas

**Comment by vichoeq** [comment]
Hola, en clases se dijo que la modelación del enunciado (dominio binario) era una mala modelación, haciendo el simil con las N reinas.

**Comment by vichoeq** [comment]
Más que una mala modelación, es posible hacer mejores modelaciones que incluyan parte de las restricciones en las variables/dominio. Nuevamente, ver N reinas.
