### ISSUE TITLE
[Tarea 3] wrong number en servidor

### ISSUE THREAD

**Issue by snarriagada** [IIC2133-PUC/2020-2#177]
Hola! Comparo en el terminal mis outputs de los test easy con sus soluciones mediante el comando diff y me arroja que son iguales. Pero para probarlo en el servidor, me arroja WRONG NUMBER en todos los test (easy, medium, hard). Significa que hay errores en mi solución? o puede ser algún otro problema.
Gracias!

**Comment by caespinoza5** [comment]
Sí, hay errores en tu solución en ese caso. Recomiendo que hagas un pequeño programa o función que revise el out.txt una vez que lo generas, que revise si estás cumpliendo todas las restricciones.

**Comment by caespinoza5** [comment]
También asegura que tu solución es la misma con y sin el visualizador (en caso de que lo estés ocupando). Para esto corre tu programa con el flag `--novis` al final.

**Comment by snarriagada** [comment]
Mmm que raro, no he hecho un programa para revisar las restricciones, pero el diff me tira igual para todas las soluciones disponibles del siding, se supone que son los mismos tests en el servidor o no?

y sin/con --novis me tira la misma solución. Puede afectar algún memory leak? hice los free correspondientes pero no los he probado con valgrind aun.

**Comment by yerkko** [comment]
Los tests de grade son secretos. Consideraste eso?

**Comment by snarriagada** [comment]
si! pero los test de http://edd.ing.puc.cl/test?repo=T3-2020-2-snarriagada  deberían ser los mismos del siding/material-tareas o no? si es así no entiendo pqe me da el mismo out.txt que la solución en mi computador y en el servidor WRONG NUMBER

**Comment by caespinoza5** [comment]
@snarriagada Probando localmente tu código en mi computador, tampoco me da un output que cumple las restricciones. ¿No habrás de casualidad sobreescrito el output esperado?

**Comment by snarriagada** [comment]
Gracias por probarlo! Con las restricciones te refieres a no modificar las casillas que vienen originalmente y que cada casilla vea su grado verdad? según he revisado mis outputs si las cumplen. Ahora puse que el visualizador muestre como me queda mi tablero final (el que imprimo en out.txt) y no veo que incumpla restricciones para los test. Adjunto foto de mi out.txt /test normal 2/ visualizador. Y sobreescribir el output esperado, te refieres a escribir sobre el txt de solución? no cache. Gracias!
<img width="849" alt="issue" src="https://user-images.githubusercontent.com/48299079/98962344-4d6c8380-24e5-11eb-9f3e-d487376ae7ec.png">

**Comment by caespinoza5** [comment]
Cuando corres `make`, ¿Te aparecen warnings? De ser así, podrías intentar arreglarlos y ver si el problema persiste.

**Comment by caespinoza5** [comment]
Recomiendo que investigues e intentes arreglar este error, que debe ser el causante:

![image](https://user-images.githubusercontent.com/26394948/98966701-57dd4c00-24ea-11eb-9e66-f46443ba3c7b.png)

**Comment by snarriagada** [comment]
Buena! eso era, arregle el warning haciendo malloc para un array que retorno y funciona perfect en el servidor ahora. Gracias!!
