### ISSUE TITLE
[Tarea 3] Datos empíricos informe

### ISSUE THREAD

**Issue by Mjtala** [IIC2133-PUC/2020-2#178]
para el informe debemos mencionar 2 podas y justificar empíricamente la utilización de estas. Hay una poda que yo quería implementar pero por falta de tiempo no lo hice, podré preguntar si alguien la hizo y pedirle los datos obtenidos, obviamente citando su tarea o eso no se puede hacer?

**Comment by caespinoza5** [comment]
Hola,

Lo discutimos como equipo docente y lamentablemente esa opción no es viable 🙁 principalmente por el hecho de que preguntar si alguien hizo X poda implicaría dar ideas sobre posibles podas a implementar a nivel de código. Además, las podas que cada uno idea es información individual.

En este caso, puedes responder todo ese punto menos los datos empíricos y tener el puntaje parcial por ello.

**Comment by sopadeoliva** [comment]
@caespinoza5 
Holaa! o sea que podemos describir paso a paso las podas o cómo funcionan en el informe a pesar de no haberlas implementado (con puntaje parcial, obviamente)? me pasa algo similar, que tengo más o menos claro cómo funcionarían estas podas pero no sé si alcance a agregarlas al código :(

**Comment by yerkko** [comment]
Yes, no hay problema con que hagan eso
