### ISSUE TITLE
[Tarea 3]

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2133-PUC/2020-2#179]
Hola,

Tengo problemas para escribir el archivo de output.txt pongo directamente:
` fprintf(output_stream,"hola\n");`  para ver si escribe algo en el txt y aun así el archivo de output esta vacío.  Tampoco, escribe la matriz en el output. ¿Qué podría estar fallando?

Gracias

**Comment by caespinoza5** [comment]
¿Te aseguraste de que tu código llega a esa línea? Podrías intentar hacer:

```c
printf("hola\n");
fprintf(output_stream, "hola\n");

```

**Comment by dpvillarroel** [comment]
Pongo `printf("hola\n");` antes y después de ejecutar mi código, pero nunca lo imprime en consola y si imprime la matriz. Entonces pasa por ahí y no imprime nada y tampoco escribe en el txt.

**Comment by caespinoza5** [comment]
Si nunca lo imprime en consola significa que no estás llegando a ese punto; revisa por qué puede pasar eso. Recomiendo que veas si el programa funciona cuando lo corres con ` --novis` al final.

> si imprime la matriz

Te refieres a que en el mismo punto donde haces `printf("hola\n")` no te imprime eso en consola pero sí la matriz? eso sería muy extraño.

**Comment by dpvillarroel** [comment]
Eso es exactamente lo que pasa.... y tengo todos estos include, no se si podría faltar algo...
`#include "../visualizer/visualizer.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "matrix.h"
#include "functions.h"
#include "show.h"
`

**Comment by caespinoza5** [comment]
Háblame por discord y lo podemos ver. Recuerda subir tus cambios al repositorio.

**Comment by dpvillarroel** [comment]
Gracias! era porque estaba compilando mal
