### ISSUE TITLE
[Tarea 3] Datos empíricos

### ISSUE THREAD

**Issue by topkaj** [IIC2133-PUC/2020-2#180]
Los datos empíricos en la justificación de las podas/heurísticas, ¿deben ser para cada uno/a por separado? ¿O basta con comparar los resultados de la aplicación con ambas mejoras vs. sin ninguna mejora?

**Comment by yerkko** [comment]
Separados, si no cómo podrías analizar el efecto individual?

**Comment by topkaj** [comment]
Vale, pero aun separados, me queda la duda si comparar cada una respecto a sin mejoras, o analizar el efecto de aplicar una y luego con ambas juntas. Lo digo porque puede que aunque ambas por separado (respecto a sin mejoras) tengan efectivamente una mejora sustancial, la suma de ambas esté más cerca de los resultados de aplicar una sola, ¿o no?

**Comment by yerkko** [comment]
Lo mínimo/esperado es analizar cada una por sí sola. Si quieres analizar el efecto conjunto está bien (y sería interesante de leer por la no-linearidad), pero no es necesario
