### ISSUE TITLE
[Tarea 3] Error en el servidor pero correcto localmente

### ISSUE THREAD

**Issue by nsolari99** [IIC2133-PUC/2020-2#181]
Hola. Cuando comparo los outputs localmente los normal y easy estan correctos. El problema es que en el servidor hay dos test que arrojan WRONG NUMBER. Revise el issue #177 y no tengo errores de memoria y con el comando Make compila perfectamente. ¿Porque podria ser esto? Ya revise harto tiempo los dos archivos y estan iguales. 
Gracias!

**Comment by caespinoza5** [comment]
Tu algoritmo está incorrecto. Ejecutando localmente tu repositorio con el archivo`easy_3.txt` me da el siguiente output (lo formateé un poco para que se viera mejor):

```
 2  1 -1  3  6  5  6
 1 -1  3 -1  5  4  5
-1 -1  7  7  7  6  7
 3 -1  5  5  5 -1  3
 6  3  6  6  -1 2 -1
 3 -1 -1  3  -1 2 -1
 3 -1 -1 -1  2  4  3
```

El 3 de la esquina inferior derecha ve a 2 celdas, no 3.

**Comment by nsolari99** [comment]
Gracias!! No sabia que habian cambiado los tests.
