### ISSUE TITLE
[Tarea 3]  Al ver resultados en Servidor tira Error

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2133-PUC/2020-2#182]
Hola!
Creo haber terminado de hacer el juego recién y quería ver mis resultados con el servidor pero no funciona. Ocupe el comando:

**curl “edd.ing.puc.cl/test?repo=XX”**

Esta linea funciona bien y dice que espere unos minutos hasta que este listo. Luego ejecuto la segunda linea:

**curl "edd.ing.puc.cl/results?repo=XX&check=test"**

Esta linea es la que me tira error con estatus: COMPILATION ERROR

**Comment by caespinoza5** [comment]
¡Hola!

Revisa si tienes `warnings` cuando corres `make` al clonar el repositorio. De ser así, intenta arregarlos; eso podría hacer que no pueda compilar en el server.
