### ISSUE TITLE
[Tarea 4] Descripción del parámetro T

### ISSUE THREAD

**Issue by szabala** [IIC2133-PUC/2020-2#184]
Hola, cuando en el enunciado dice "[...] T representa el alto y ancho del tablero.." hace referencia a la cantidad de puntos que hay en una fila y columna o a la distancia? En el ejemplo del enunciado:

![image](https://user-images.githubusercontent.com/48331715/100012354-e5a21c80-2db1-11eb-83aa-59477ccfeeba.png)

Si T=2 fuera la cantidad de puntos, (2, 0) estaría fuera del tablero. Mi duda surge por el ejemplo de debug:

![image](https://cdn.discordapp.com/attachments/739925719659970640/780529486844264448/unknown.png)

Es coincidencia que en este ejemplo no hayan puntos donde la fila o columna sea igual a 3?

**Comment by caespinoza5** [comment]
¡Hola!

Considéralo como la distancia (y que en el caso del debug es coincidencia). Si T = 2 sabes que un punto tendrá como máximo una fila = 2 y/o columna = 2, pero puede no necesariamente ocurrir.
