### ISSUE TITLE
[Tarea 4] Variación del Parámetro Rango en Kruskal

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#185]
Hola!

Hoy vimos que cuando ejecutamos find-set(), además de encontrar el representante del subconjunto, aprovechamos de hacer más compacto el árbol. Mi duda es si hacemos esto en algunas ocasiones variaremos el rango del subconjunto, por ejemplo si, después de la operación, todos los nodos hijos se encuentre a un rango menor que el original. ¿Cómo el algoritmo de Kruskal compensa esta situación, es decir, find-set debe encargarse de revisar todo el árbol y revisar el rango actual máximo? Lo pregunto porque si no actualizo este valor la función unión podría tener ineficiencias más tarde.
Para que se entienda si aplico find_set(A) en el grafo de la figura, su rango disminuye de 2 a 1. 

![image](https://user-images.githubusercontent.com/34272957/100015896-67487900-2db7-11eb-89be-42262ae11486.png)

Gracias de antemano.

**Comment by vichoeq** [comment]
Hola, el rango de un conjunto disjunto es una cota superior de la altura del arbolito: en ningun momento conocemos la altura real del conjunto. Como tu dices, al acortar A, **deberia** disminuir el rango de F, pero esto no pasa: F se queda con su rango 2 por el resto de la ejecución del algoritmo. Mantener calculada la altura real del árbol es mucho más costoso que mantener el rango y no hace que el algoritmo sea más rápido: las complejidades que les dimos de cada operacion son considerando esto.

**Comment by fnberrios** [comment]
De acuerdo, genial. Gracias por la aclaración.
