### ISSUE TITLE
[Tarea 4] Error en el servidor

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2133-PUC/2020-2#186]
Quería preguntar sobre el error del server INCORRECT NUMBER OF EDGES, que me sale en todos los tests. 
Para el MST básico, sin Steiner Points, mi código me entrega el peso total del árbol bien, el que indica la primera línea de los tests. Pero este error me aparece en el servidor. Mis MST tienen N - 1 aristas, y todas aparecen bien en el output (según lo que revisé localmente). No sé muy bien a qué se refiere el error, porque creí que estaba bien esa cantidad de aristas.
aiuda? 😥

**Comment by caespinoza5** [comment]
¿Tu output tiene el número total de puntos de tu grafo al inicio? ¿Comparaste tu output con los dos outputs de los tests debug?

**Comment by sopadeoliva** [comment]
Me pasa que en el archivo de debug, que son 4 puntos equidistantes tengo esto: (la primera es el archivo debug, sin steiner points, la segunda es el de mi programa)
<img width="192" alt="Captura de Pantalla 2020-11-28 a la(s) 10 26 20" src="https://user-images.githubusercontent.com/42161679/100516703-6e2f0d00-3164-11eb-8221-306813a689de.png">
<img width="155" alt="Captura de Pantalla 2020-11-28 a la(s) 10 26 28" src="https://user-images.githubusercontent.com/42161679/100516704-6f603a00-3164-11eb-8749-f19f426b3aa7.png">
No entiendo por qué el del archivo debug da 4 como respuesta, si el peso total de los puntos que tiene es 6. Pero igual aparecen todos los puntos :0

**Comment by caespinoza5** [comment]
El primer valor del output equivale al número de puntos totales, no al puntaje. El puntaje lo calculamos nosotros en base a las aristas que describen. Por lo mismo `debug_a.txt` tiene 4 puntos ((1,0), (0,1), (1,2), (2,1)), y ese es el primer valor.

**Comment by sopadeoliva** [comment]
aaaaa, eso no lo había entendido :) gracias, perdón por la confusión

**Comment by caespinoza5** [comment]
¡De nada! Solo para complementar, el error "INCORRECT NUMBER OF EDGES" se da porque si tu número inicial es N, el programa corrector espera N - 1 aristas, y si tu cantidad de aristas es distinto a N - 1 te tirará ese error.

**Comment by arpincheira** [comment]
Hola, el cuales son las posibles causas que podrían provocar este output?: "OUTPUT IS NOT MST"

**Comment by caespinoza5** [comment]
Hola @arpincheira ,

Ese error significa que, si yo obtengo el conjunto de puntos pertenecientes a las aristas que me entregas, puedo encontrar un árbol de cobertura mínimo cuyo costo mínimo es menor al que tu me das con tus aristas.
