### ISSUE TITLE
Cantidad máxima de aristas por vertice MST [Tarea 4]

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2133-PUC/2020-2#187]
Una consulta. El máximo de aristas por cada vértice es de 4 o no en un MST con costo basado en la distancia?? Confirmar esto me es importante para modelar como encontrar los steiner points.

**Comment by vichoeq** [comment]
Tendria sentido. Que tal si trabajas, codiciosamente, asumiendo que esto se cumple?
