### ISSUE TITLE
[Duda C] [make] /usr/bin/ld: cannot find -lpng

### ISSUE THREAD

**Issue by lzalaquett** [IIC2133-PUC/2020-2#23]
[Plataforma de C] = Terminal de Ubuntu 

Hola, Creo que estoy tenbiendo problemas para compilar con `make`.

Trato de seguir las instrucciones que salen en el readme del repo de la tarea. 
Entonces, pongo `make` y me tira:

```
 /usr/bin/ld: cannot find -lpng
 collect2: error: ld returned 1 exit status
 Makefile:119:` recipe for target 'simulate' failed
 make: *** [simulate] Error 1
```

Y creo que en lo anterior está el problema. 
Pero tambien se creó una dirección `obj/simulate` y dentro se me creó `cell.o`, `main.o` y `mould.o`.

Luego pongo `./simulate tests/test.txt out_C.txt` y me dice `bash: ./simulate: No such file or directory
`
Después corro el python con `python3 python/simulate.py tests/test.txt out_python.txt` y sí funciona bien. 

Entonces creo que mi problema es con compilar con `make` y que no está pasando lo que debería pasar.

Saludos

Demería instalar la librería PNG? o no tengo que hacer nada y ponerme a programar nomás?

**Comment by caespinoza5** [comment]
¿Revisaste [esta guía](https://github.com/IIC2133-PUC/2020-2/blob/master/Gu%C3%ADas/Setup/3.0%20GTK.md) y [esta issue](https://github.com/IIC2133-PUC/2020-2/issues/11)?

**Comment by lzalaquett** [comment]
Muchas gracias. 
Efectivamente no había hecho nada de eso. 
creí que con linux solo tenía que descargar valgrind.

quedó solucionado.
