### ISSUE TITLE
[Duda C] connot find -lpng

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#28]
[Plataforma de C] = WSL

Hola! Estaba tratando de compilar mi programa de la T0 y al momento correr make en el terminal obtengo el siguiente mensaje:
![image](https://user-images.githubusercontent.com/34272957/90462193-514f5c00-e0d6-11ea-9cbe-579671453e26.png)
Investigué y según Google me falta incluir una librería, pero no estoy seguro cual ni donde porque no se menciona cual es la que falta. ¿Cómo podría solucionarlo?
Descubrí que en el Makefile aparece la libreria:
![image](https://user-images.githubusercontent.com/34272957/90462413-cf136780-e0d6-11ea-816d-3510d511efdf.png)

**Comment by caespinoza5** [comment]
¿Revisaste [esta guía](https://github.com/IIC2133-PUC/2020-2/blob/master/Gu%C3%ADas/Setup/3.0%20GTK.md) y [esta issue](https://github.com/IIC2133-PUC/2020-2/issues/11)?

**Comment by fnberrios** [comment]
Oh... Toda la razón. Gracias! @caespinoza5
