### ISSUE TITLE
Tarea 0 - Análisis

### ISSUE THREAD

**Issue by SergioGazali** [IIC2133-PUC/2020-2#29]
Hola! Respecto al análisis de la complejidad de cada evento, siento que puedo evaluar los algoritmos de más de una manera. Una forma podría ser una secuencia simplificada de pasos (podrían pensarse como los pasos "teóricos" del algoritmo, o bien los que se hacen en python, que es de mayor nivel que c), y otra forma sería la del algoritmo en concreto que estoy haciendo en c. Por ejemplo, hay un evento en que se recorre cierta parte del árbol para luego hacer una operación. Esto, teóricamente y en python, se podría pensar como la complejidad de ese recorrido, y un paso más que es la operación. En c, en cambio, luego de hacer el recorrido, para esa operación en sí hago nuevos recorridos de la estructura porque me estoy haciendo cargo de la memoria. 
Debiera estar considerando en la complejidad del algoritmo este último recorrido por la estructura, que es propio de mi implementación en c? o simplemente estudiar el algoritmo en su versión teórica (en que no tengo que liberar memoria)?

**Comment by caespinoza5** [comment]
Hola,

Deja especificado en tu informe bajo qué supuesto lo escribirás: a nivel de teoría o a nivel de programa. Se te corregirá en el contexto de tus supuestos; mientras las complejidades calculadas tengan sentido bajo tu supuesto, estaría bien.

**Comment by caespinoza5** [comment]
Dicho lo anterior, es sumamente importante que leas en detalle el evento. Si en el evento se considera la eliminación de hijas, es necesario que consideres esto en el cálculo, independiente si estás calculando a nivel teórico o práctico.
