### ISSUE TITLE
Tarea 0 error: invalid application of 'sizeof' to an incomplete type 'struct cell'

### ISSUE THREAD

**Issue by elisafdz** [IIC2133-PUC/2020-2#35]
Hola!
definí los structs Cell y Mould en los archivos correspondientes y luego al intentar inicializar el mould metiera el siguiente error: invalid application of 'sizeof' to an  incomplete type 'struct cell'. Lo busqué en internet pero no logro solucionarlo por lo que agradecería mucho si me pueden ayudar.

Gracias!

**Comment by Kitaps** [comment]
Hola, hablame por discord para que lo veamos ;)
