### ISSUE TITLE
Función delete de python Tarea 0

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2020-2#36]
Hola, en el enunciado de la tarea, el enunciado de la tarea dice que el comando BUD debe eliminar todos los nodos hijos de la celula a eliminar, como sale en el ejemplo:
![image](https://user-images.githubusercontent.com/42189869/90831147-1422de00-e311-11ea-95b7-576b846d11a7.png)
Sin embargo, mirando el archivo simulate.py y la función de cell.delete(idx)
![image](https://user-images.githubusercontent.com/42189869/90831300-6fed6700-e311-11ea-9bd7-849deee14475.png)
Lo que me hace entender que solo se esta eliminando la célula hija correspondiente a idx y según a mi parecer debería ser algo recursivo o iterativo que elimine también las celulas hijas de la celula hija en idx. No se si me podrían aclarar un poco más aquella parte.
Gracias de antemano.

**Comment by caespinoza5** [comment]
Toda la memoria que queda guardada en tu ejecución de un programa en python, al finalizar el programa se libera (aunque no necesariamente de una manera eficiente). Es parte de la tarea que ustedes implementen esa eliminación recursiva en su programa en C, ya que python maneja eso por atrás.

**Comment by Tngarrido** [comment]
buenísimo! @caespinoza5  ahora si me quedo claro.
