### ISSUE TITLE
Tarea 0: Evento Absorb (código entregado)

### ISSUE THREAD

**Issue by joseh20p** [IIC2133-PUC/2020-2#38]
Tengo una duda con respecto al código entregado en main.c, en el apartado de Absorb luego de obtener la dirección de la cell2 lee nuevamente un número decimal, donde a mi parecer no debería leer nada.
Adjunto imagen de referencia.
![duda t0](https://user-images.githubusercontent.com/48306414/90992221-dffb2780-e573-11ea-9e48-7530636c7cac.PNG)

**Comment by caespinoza5** [comment]
Ojo que si te fijas, el `for` anterior va hasta depth - 1, por lo que esa última sí está bien y es efectivamente el fin del camino de la célula.

**Comment by joseh20p** [comment]
aaa muchras gracias!!
