### ISSUE TITLE
Problema al ejecutar programa en Maquina Virtual

### ISSUE THREAD

**Issue by pablovejar** [IIC2133-PUC/2020-2#39]
[Sistema Operativo] = Mac OS X

Hola! He estado tratando de ocupar valgrind para ver los errores de memoria en mi código pero me está pasando que ni siquiera puedo hacer el "make" de mi tarea. Cada vez que pongo make me tira el siguiente error:

```
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
make: *** [Makefile:119: simulate] Error 1
```
No me genera el archivo simulate, ya he buscado por todos lados y no encuentro solución.

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

¿Buscaste en las issues del curso?

**Comment by pablovejar** [comment]
Ahora encontré una que es parecida a mi problema! No había revisado bien, sorry :)

**Comment by caespinoza5** [comment]
Super! Y favor no cerrar issues,  por si otra persona tiene el mismo problema en el mismo sistema operativo 😄
