### ISSUE TITLE
[Tarea 0] - Cantidad de casos de comparacion ejecucion con Python

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#40]
Para los casos de ejecucion a comparar, hay alguna cantidad recomendada?

**Comment by caespinoza5** [comment]
Utiliza la cantidad de casos necesaria para fortalecer tu argumento. En particular, si hay tests muy pequeños y la diferencia no es notable, puedes quizás no ocupar esos si no favorece tu argumento. Lo importante es que, si tu argumento es que hay diferencias notables (o no) de tiempo, lo puedas justificar con los datos (ya sea en tablas, gráficos, etc)

**Comment by vichoeq** [comment]
Para comparar ejecución con python, lo que importa es el tiempo. Porque en cantidad de pasos / lineas de código de código, probablemente en C hagas más porque es más verboso. Lo que importa es medir el impacto de las cosas que hace Python por detrás.
