### ISSUE TITLE
Evento "ABSORB"

### ISSUE THREAD

**Issue by maormeno** [IIC2133-PUC/2020-2#42]
En el enunciado dice "Todas las CELLS que se encuentran entre la CELL1 y la CELL2 y sus respectivas hijas son
eliminadas.".... se entiende como que TODAS las hijas de CELL1 son eliminadas a excepción de CELL2? (osea que TODAS las hijas de CELL2 también son eliminadas).
O se elimina solo el "tramo" entre CELL1 y CELL2 y CELL2 conserva sus hijas en su nueva posición??

**Comment by caespinoza5** [comment]
Se elimina sólo el tramo entre CELL1 y CELL2 (y sus respectivas hijas), excepto CELL2. En la imagen del enunciado debería quedar más claro; si no, en el código de python puedes ver la lógica detrás del algoritmo.

**Comment by maormeno** [comment]
Justo el "respectivas hijas" me confundía jajajaj, entonces CELL2 conserva sus hijas al ser desplazada a su nueva posición?

**Comment by caespinoza5** [comment]
Así es! Las conserva. Ignorando los índices, si tienes un mould así:
A->B->C->D->E->F->G
Y haces un ABSORB de tal manera en que eliminas el tramo B->C->D, el mould quedaría así:
A->E->F->G

**Comment by maormeno** [comment]
Perfecto, muchas gracias!!!
