### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by Mjtala** [IIC2133-PUC/2020-2#43]
windows-visual code
Hola!
Cuando trato de usar  valgrind --leak-check=full me tira este error y nose cómo solucionarlo.
error calling PR_SET_PTRACER, vgdb might block
Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Ese error lo puedes ignorar, y no afecta ni en los leaks de memoria ni en los errores de memoria :)
