### ISSUE TITLE
Tarea 0

### ISSUE THREAD

**Issue by Arodriguez14** [IIC2133-PUC/2020-2#48]
Tu duda acerca de la T0 acá.

Hola, tengo este error al hacer make y no he podido solucionarlo. Instale todo lo de la guia y me funciona perfecto en los codigos de la ayudantía.

![Captura de pantalla 2020-08-25 a la(s) 16 49 27](https://user-images.githubusercontent.com/48296628/91227682-ea90fa80-e6f4-11ea-9fe4-43e9a4caa2f0.png)

**Comment by caespinoza5** [comment]
¡Hola!

Recomiendo que busques en otras issues del repositorio; me cuentas si investigando ahí aún tienes la duda.
