### ISSUE TITLE
Diferencias en spacing de soluciones de siding y codigo de python

### ISSUE THREAD

**Issue by ibaeza1** [IIC2133-PUC/2020-2#49]
Hola! 
Estaba probando los tests que estan en el siding y viendo las diferencias entre mi out_C.txt y las soluciones que estan subidas y note que la hacer 
`diff --strip-trailing-cr out_C.txt hard_test_4.txt`
que seria comparar mi archivo out_C.txt con la solucion subida al siding del hard_test_4 me sale que no hay diferencias, pero si ejecuto este test en el codigo de python y luego hago
 `diff --strip-trailing-cr out_C.txt out_python.txt`
para comparar mi out_C.txt con el archivo que me retorna python, me sale que es distinto ya que el spacing de la funcion observe tiene un espacio menos en el codigo de python y en las soluciones subidas al siding tiene un espacio mas.
El contenido del observe es el mismo asi que el resultado esta bien pero los spacings estan distintos entonces me sale que es todo diferente.
Por cual me tengo que guiar para comparar? Por el out_python o por las soluciones del siding?
Gracias! :)

**Comment by caespinoza5** [comment]
Es muy extraño que tengan distinto resultado; localmente los resultados son iguales. En todo caso, deberías guiarte con el espaciado de python (3 espacios por cada `spacing`).
