### ISSUE TITLE
TO: Warning al hacer make

### ISSUE THREAD

**Issue by dtgazmuri** [IIC2133-PUC/2020-2#50]
Hola
Cuando ejecuto el comando make, mi programa se compila pero me arroja unos warnings que no comprendo. Adjunto foto de esto por si alguno de ustedes entiende cuál es el problema.
Gracias

![Screen_Shot_2020-08-25_at_19 37 18](https://user-images.githubusercontent.com/53804308/91238218-8aa54e80-e70a-11ea-9ed6-80219a27500d.png)

**Comment by caespinoza5** [comment]
¡Hola!

Esos warnings son por módulos que vienen en la Makefile (`-lm` para el módulo de matemática de C), que no fueron ocupados. Esos módulos se nos olvidó sacarlos de la Makefile :sweat_smile:, pero los pueden ignorar; no afectan en la ejecución del programa, ni leaks de memoria ni errores de memoria.

¡Saludos!

**Comment by dtgazmuri** [comment]
Vale, gracias!
