### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by narierao** [IIC2133-PUC/2020-2#54]
[Plataforma de C] = La plataforma en la que estas corriendo C 

Hola! tengo mi tarea lista (al menos me corre con gcc main.c -o main) y luego cuando le hago valgrind está todo ok. No sé como puedo hacer funcionar el comando make :c si alguien pudiese ayudarme orientándome en qué carpeta debo correr el comando o si debo modificar el MakeFile sería de mucha ayuda.

Gracias!

**Comment by caespinoza5** [comment]
¡Hola! El comando `make` deberías correrlo en la carpeta donde está la `Makefile`. Me avisas qué tal te va. Si te dice que no tienes la librería `lpng`, ruego que revises otras issues de la tarea.

**Comment by narierao** [comment]
Hola! este es el error que me aparece :c 

![image](https://user-images.githubusercontent.com/20784195/91607956-b3178d80-e942-11ea-9a81-974d5cfb05e8.png)

**Comment by caespinoza5** [comment]
¡Hola!

Eso es un warning; simplemente te dice que tienes una variable que no utilizaste. ¿Te funciona el programa?

**Comment by narierao** [comment]
Mira, estos son los comandos que ejecuto:
![image](https://user-images.githubusercontent.com/20784195/91610499-59659200-e947-11ea-895c-b66bbaf53767.png)
Y este es el resultado :c 
![image](https://user-images.githubusercontent.com/20784195/91610559-77cb8d80-e947-11ea-9b11-375af15eb169.png)

**Comment by caespinoza5** [comment]
Ah pero ahí estás llamando desde main. Intenta cambiar a la carpeta principal (`T0-2020-2-narierao`) y ejecuta make ahí; muestrame qué te aparece.

**Comment by narierao** [comment]
![image](https://user-images.githubusercontent.com/20784195/91610901-1d7efc80-e948-11ea-9d11-e76cf655c826.png)
Eso es lo que me aparece :/

Como dato, dejé la mayoría de las funciones en los archivos .h para que las reconocieran los otros programas (las dejé definidas solo ahí).

**Comment by caespinoza5** [comment]
La función `init_cell` la tienes definida más de una vez? Revisa que estés importando bien los archivos y que no estés definiendo cosas en los .h, si no solo en los .c. Asegura de no estar importando los .c en ningún lado.

Por ejemplo, para `cell` lo normal sería:

Declarar las funciones en el .h:
`Cell* init_cell(tipo1 var1, tipo2 var2);`

Definir las funciones en el .c, importando el .h:


```
#include "cell.h"
Cell* init_cell(tipo1 var1, tipo2 var2)
{
// Defines tu función
} 
```

Y luego incluir `cell.h` en los archivos donde lo necesites (`mould.c`, `main.c` por ejemplo).

**Comment by narierao** [comment]
Gracias! ahí me funcionó <3<3<3<3
Ahora veré el tema de lpng.
Te pasaste!
