### ISSUE TITLE
Tarea 0 Tiempo Maximo?

### ISSUE THREAD

**Issue by MINGOD24** [IIC2133-PUC/2020-2#56]
Hola, quería saber si existe un tiempo máximo para correr el programa. :)

**Comment by caespinoza5** [comment]
Sí; tal como menciona el enunciado, son 10 segundos máximo por archivo de input.

**Comment by MINGOD24** [comment]
Donde sale? Lo he buscado pero no veo nada relacionado a eso. Y en caso de ser asi, si mi hard test demoran 10.5 segundos como maximo(de repente demora menos), estaria mal?

**Comment by caespinoza5** [comment]
:open_mouth: Tienes toda la razón! Si bien se habla de que sea eficiente en sección de evaluación, no se especifica cuán eficiente; mil disculpas. En sí, tu programa deberá ser capaz de pasar todos los tests antes de 10 segundos por archivo. Si consideras que tu computador es lento (o estás ocupando una máquina virtual), ruego que pruebes tu programa en el servidor que habilitamos. Puedes encontrar información [aquí](https://github.com/IIC2133-PUC/2020-2/issues/53).

**Comment by MINGOD24** [comment]
@caespinoza5 Toda la razon! lo probe en el servidor y me sale que se demora muchisimo menos que lo que salia en mi pc. Muchas gracias!

**Comment by caespinoza5** [comment]
¡Súper! De nada 🙂
