### ISSUE TITLE
[SERVER] Test Hard 3

### ISSUE THREAD

**Issue by andresplass** [IIC2133-PUC/2020-2#57]
Hola buenos dias, estaba analizando los tests y grades en el servidor, y con los tests de siding me sale todo bien!
Pero en /grades me sale un solo error en el hard test 3. Lo extraño es que en ambos intentos, todos los tests se demoran el mismo tiempo (en /test y /grades) excepto hard test 3 que en /grades se demora más que en /test. 
Queria saber si (quizas) habia un problema con ese test, o me meto a investigar qué puede estar mal con mi código, ya que encuentro raro que solo esté ese malo.
Muchas gracias!

**Comment by caespinoza5** [comment]
Recomiendo que investigues qué podría estar mal, ya que el test está bien. ¿Valgrind te da 0 errores?

**Comment by andresplass** [comment]
sii, me dió 0 errores

**Comment by caespinoza5** [comment]
Entonces no estoy muy seguro qué podría ser. Te recomiendo comparar con el código de python y ver si estás haciendo exactamente lo mismo; si quedas medio estancado, contáctame por discord.

**Comment by andresplass** [comment]
Yaa muchas gracias! veré que puede ser 😄

**Comment by ibaeza1** [comment]
hola! a mi me pasa lo mismo con el test hard 3 y el 4. En los tests del siding me sale que esta todo bien y valgrind tambien me tira 0 errores pero en esos dos tests de grade me sale wrong output. Revise el codigo de python y esta todo igual asi que en verdad no se que esta mal. Hay alguna forma de ver el error que tiran esos tests en el servidor?.
Gracias! :)

**Comment by caespinoza5** [comment]
¡Hola!

¿En qué sistema operativo están trabajando? Al clonar sus repositorios y ejecutar valgrind con ellos (`valgrind ./simulate tests/test.txt out.txt`) me salen bastantes errores, lo que produce que se caiga en el servidor su programa.

**Comment by andresplass** [comment]
Yo en windows con wsl2, pero lo encuentro raro, no me sale ningun error en ningun test, y con valgrind sale 0 memory leaks

**Comment by ibaeza1** [comment]
Yo tambien con wsl2 pero no me sale ningun error tampoco me salen errores.
![image](https://user-images.githubusercontent.com/37149485/91469440-6445f700-e861-11ea-87fd-dd377edad077.png)
Dice en el SUMMARY que hay 0 errores asi que asumo que eso es que no hay jaja.

**Comment by andresplass** [comment]
> ¡Hola!
> 
> ¿En qué sistema operativo están trabajando? Al clonar sus repositorios y ejecutar valgrind con ellos (`valgrind ./simulate tests/test.txt out.txt`) me salen bastantes errores, lo que produce que se caiga en el servidor su programa.

Ahí ejecuté valgrind con el hard test y efectivamente tira errores de memoria. El output obtenido es correcto pero el problema puede ser el tema de la memoria.

Alguna recomendación para solucionar estos errores de codigo?

**Comment by caespinoza5** [comment]
@ibaeza1  Ojo! `0 errors from 0 contexts` es que no tiene errores de memoria, pero si en `LEAK SUMMARY` no te aparece `All heap blocks were freed -- no leaks are possible` significa que aun tienes leaks de memoria. Esto causa que tu programa se pueda caer en otros sistemas operativos.

Para solucionar esos errores, recomiendo que vayan viendo los `free`s, `alloc`s y `malloc`s de su programa, e ir probando con tests pequeños (incluso pueden crearlos ustedes mismos) para ver dónde están los errores. Además, les recomiendo ver las cápsulas de C disponibles [aquí](https://github.com/DCCentral-de-Apuntes/intro-C/blob/master/README.md) (en especial Memoria, Valgrind, Structs) y jueguen un poco con los archivos disponibles [aquí](https://github.com/IIC2133-PUC/2020-2/tree/master/Ayudant%C3%ADas/Ayudant%C3%ADa%200%20-%20Intro%20a%20C/Aprende%20C) (en especial 6_memoria y 7_structs).

**Comment by caespinoza5** [comment]
@andresplass Luego de revisar más en detalle sus códigos, me percaté que la razón más probable que sus programas tienen esos tests erróneos es por que están solicitando mucha memoria al servidor (sobre 1.5GB que es un límite que tenemos por cada input). Revisa si estás solicitando memoria de más. Un indicador de que podrían estar solicitando más memoria de la necesaria es si, por ejemplo, en cada célula guardas 10 estructuras de otras células, en vez de 10 punteros a otras células.

**Comment by andresplass** [comment]
Ya muchas gracias por el tiempo, revisaré eso. 😊
