### ISSUE TITLE
Tarea 0: medir tiempos usando el comando time

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2133-PUC/2020-2#58]
Hola, quería saber cuando mido los tiempos de ejecución de un programa, qué tiempo debo considerar, el real, el total, todos?
real    0m32.160s
user    0m27.820s
sys     0m0.211s

Gracias de antemano!

**Comment by caespinoza5** [comment]
Se utiliza el real 🙂 

¡Saludos!

**Comment by kmhaller** [comment]
hola, da lo mismo si puse todos?

**Comment by caespinoza5** [comment]
Da lo mismo 😃
