### ISSUE TITLE
[Administrativo] Ubicación Carpeta Códigos

### ISSUE THREAD

**Issue by fnberrios** [IIC2133-PUC/2020-2#6]
Hola! Quiero hacer los ejercicios para probar la instalción de Ubuntu en mi pc, pero no encuentro la carpeta Código. ¿Aún no la suben?
![image](https://user-images.githubusercontent.com/34272957/89940094-fce44200-dbe6-11ea-9383-11485f576b62.png)

**Comment by yerkko** [comment]
Our bad. Fíjate en

**Comment by vichoeq** [comment]
Si, la guía está desactualizada (actualizando ahora). 

En particular los ejemplos a los que se refiere esa guía están en la carpeta [Prueba tu setup](https://github.com/IIC2133-PUC/2020-2/tree/master/Ayudant%C3%ADas/Ayudant%C3%ADa%200%20-%20Intro%20a%20C/Prueba%20tu%20setup)

**Comment by fnberrios** [comment]
@yerkko @vichoeq Gracias!
