### ISSUE TITLE
Error python 3 linux subsystem

### ISSUE THREAD

**Issue by patogramador** [IIC2133-PUC/2020-2#60]
Hola! me tira este error al correr el codigo de python3 que esta en el readme de la tarea. Alguna idea porque puede ser?
![error python3](https://user-images.githubusercontent.com/48293109/91485648-2785fa00-e879-11ea-85dd-95b0fccf5007.PNG)
Este es el codigo que me refiero:
python3 python/simulate.py tests/test.txt out_python.txt

**Comment by caespinoza5** [comment]
Probablemente tienes desactualizado `python3`. Intenta ejecutar estos dos comandos:
`sudo apt update -y`
`sudo apt install python3.7`

**Comment by patogramador** [comment]
Sigue tirando el mismo erro :(

**Comment by caespinoza5** [comment]
Recomiendo que veas la alternativa que sugerí en [esta issue](https://github.com/IIC2133-PUC/2020-2/issues/59), por si no logras actualizarlo.

**Comment by patogramador** [comment]
Con esos cambios me funcionó, gracias!
