### ISSUE TITLE
Tarea 0: comparación python y C

### ISSUE THREAD

**Issue by Juan379** [IIC2133-PUC/2020-2#64]
Hola! Es necesario comparar los tiempos para todos los archivos de prueba subidos al siding?

**Comment by caespinoza5** [comment]
¡Hola!

Utiliza la cantidad de archivos que creas razonable para justificar la diferencia de tiempo. Si solo muestras un test, por ejemplo, podría ser mera coincidencia que uno se demora más (o lo mismo) que el otro; ocupa los necesarios para ver algún patrón.
