### ISSUE TITLE
[SERVER] Usuario Inexistente

### ISSUE THREAD

**Issue by benjaurr** [IIC2133-PUC/2020-2#66]
Hola! Estoy probando usar el servidor, y al usar test o grade, la página me dice usuario inexistente, y no puedo realizar las pruebas. El link que estoy ocupando es http://edd.ing.puc.cl/test?repo=T0-2020-2-benjaurr.

**Comment by caespinoza5** [comment]
¡Hola!
Acabo de agregarte al servidor. ¿Puedes revisar si te funciona?

**Comment by benjaurr** [comment]
Ahi me funciona, muchisimas gracias!
