### ISSUE TITLE
[Tarea 1] habrán tests?

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#70]
Habran tests para la T1? 
Para la comparacion empirica, se deben usar solo los 3 tests que vienen, crear propios, o usar tests que suban?

**Comment by vichoeq** [comment]
Hola, del anuncio de SIDING para la tarea (que debería haberles llegado a todos por correo)

> Antes del martes de la próxima semana estará disponible el servidor para la tarea, archivos de tests en Siding y un video explicativo para orientarlos.

El video ya está, los tests los subiré hoy y el server debería estar habilitado poco despues de que subamos los tests.

Saludos!
