### ISSUE TITLE
Tarea 1 - particle_boundingbox_collision

### ISSUE THREAD

**Issue by SergioGazali** [IIC2133-PUC/2020-2#71]
Hola!
La función particle_boundingbox_collision retorna `true` solo si la partícula está chocando con los bordes de la caja? o si está dentro de estos bordes también? (o sea si la partícula está en cualquier lugar adentro de la caja)
Muchas gracias!

**Comment by yerkko** [comment]
Cubre todos los casos posibles. Tanto bordes como contención, tanto del círculo por la caja, como de la caja por el círculo

**Comment by JJJGGGG** [comment]
Hola

Tengo la misma duda pero para particle_segment_collision: si el segmento está contenido a medias, se considera como colisión? Gracias

**Comment by yerkko** [comment]
También se consideraron todos los casos posibles
