### ISSUE TITLE
[Setup] Problema al instalar VcXsrv

### ISSUE THREAD

**Issue by ibaeza1** [IIC2133-PUC/2020-2#72]
[Sistema Operativo] = Windows 10 Wsl2 Ubuntu 18.04

Hola! estoy tratando de instalar VcXsrv y descargue el instalador y puse la configuracion que decia en el repo pero cuando trato de correr me sale esto:
![image](https://user-images.githubusercontent.com/37149485/92508308-d19d4480-f1de-11ea-88d8-635ef3763212.png)

No entiendo por que me sale si no lo habia corrido antes.
Por que podria ser?
Gracias! :)

EDIT: Me di cuenta que pasa cuando le pongo la configuracion que me piden en el repo. Si la dejo con display:-1 y con lo que viene predeterminado si corre el servidor.

**Comment by jfernandez7** [comment]
Hola! @ibaeza1 te podría pedir que me ayudaras? Tengo exactamente el mismo problema pero no lo logré solucionar con lo que dijiste en el edit. Quizas hay algo más que cambiar?

**Comment by ibaeza1** [comment]
> Hola! @ibaeza1 te podría pedir que me ayudaras? Tengo exactamente el mismo problema pero no lo logré solucionar con lo que dijiste en el edit. Quizas hay algo más que cambiar?

Al final era porque tenia el server corriendo como por detras y no me habia dado cuenta jeje. 
![image](https://user-images.githubusercontent.com/37149485/92513986-8cc9db80-f1e7-11ea-9f72-63de97fa4666.png)

En esa parte abajo si pones la flechita te deberia salir el server corriendo (al principio no me fije que estaba corriendo porque puse la flechita y no me salia asi que tuve que ponerque me mostrara todo lo que estaba corriendo) , ahi haces click derecho en el icono de vcxsrv y exit. No se si te sirva pero eso fue lo que me sirvio a mi.

**Comment by jfernandez7** [comment]
Los cerré de otra forma y ya no me sale ese error! Gracias igual, sigo sin saber por qué no me muestra la ventana eso sí.
