### ISSUE TITLE
[Tarea 1] Sobrelapamiento de segmentos

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2133-PUC/2020-2#73]
Hola. Es posible que dos (o más) segmentos se sobrelapen de esta forma en algún test?
![image](https://user-images.githubusercontent.com/48324565/92541954-d503f080-f21d-11ea-9713-78d360da4193.png)
Es decir, tener dos segmentos estilo ```((x1, y1), (x2, y2))``` y ```((x1,y2),(x2,y1))``` o similar

EDIT:
Ya ví que demo_2.txt tiene esto. Sin embargo, podrán haber más de 2 líneas intersectandose en un mismo lugar a la vez? Hay algún límite de líneas que pueden hacer eso, o podemos asumir que 2 es el máximo?

**Comment by Kitaps** [comment]
Puede haber sobrelapamiento, y es posible que haya más.

**Comment by vichoeq** [comment]
Hola! Como ves en demo_2 hay segmentos que se traslapan. Para efectos prácticos de los tests, **eso no ocurrirá**, pero si ocurre que los segmentos compartes vértices así que _técnicamente_ se están intersectando.

Para efectos del análisis de complejidad de tu árbol, puedes asumir que no hay intersección de segmentos.
