### ISSUE TITLE
'cairo.h' file not found

### ISSUE THREAD

**Issue by kmhaller** [IIC2133-PUC/2020-2#75]
[Mac - Tarea 1] 
Hola, pasa que al hacer make después de descargar los archivos
me aparece el siguiente error:
fatal error: 'cairo.h' file not found
#include <cairo.h>
Lei que puede ser que falte instalar algo aquí (https://github.com/Homebrew/legacy-homebrew/issues/14123), 
pero no prece ser muy seguro.
¿Qué me puedo hacer?

**Comment by yerkko** [comment]
Hola, revisaste la guía de instalación de GTK?

**Comment by kmhaller** [comment]
Hola,
hice "brew reinstall jpeg" y se solucionó.
Gracias.
