### ISSUE TITLE
Tarea 1 [visualizer_draw_box ]

### ISSUE THREAD

**Issue by fivaldivia** [IIC2133-PUC/2020-2#78]
Hola, para dibujar mis cajas esta bien que haga solo esto, ya que se me dibujan blancas no de color:
```
visualizer_set_color(double 51.0,double 244.0,double 255.0);
visualizer_draw_box(node->caja);
```
Gracias!

**Comment by fivaldivia** [comment]
Ahora sí me funciona! Sorri, no me funcionaba con los demo...

**Comment by vichoeq** [comment]
Hola, los canales RGB con double van de 0 a 1! Also no es necesario que incluyas la palabra "double" antes de cada valor.

**Comment by fivaldivia** [comment]
Ya bacan gracias!

**Comment by vichoeq** [comment]
Pa no tener que calcular los numeros los puedes dividir por 255, asi te queda 51.0/255.0, 244.0/255.0, 255.0/255.0
