### ISSUE TITLE
Tarea 1 [función que retorna struct]

### ISSUE THREAD

**Issue by fivaldivia** [IIC2133-PUC/2020-2#79]
Hola, estoy teniendo problemas cuando retorno una struct Segment de una función. Por ejemplo, quiero retornar el segment en la posicion 0 de una lista de segments. Si pongo return segments[0], en mi  otra función donde lo necesito como que no se retorna el segmento. Mi función esta definida como ```struct segmente nombrefuncion()```.
Probe con punteros, sin punteros y no me funciona. Esto es lo que me pasa, al implimir el id del segmento en las funciones respectivas:
```
ID segmento  2 (e funcion)
MAL : ID  Segmento -16777728 (en otra funcion donde necesito el struct)
```
Gracias!

**Comment by vichoeq** [comment]
Y en la funcion en la que quieres retornar este segmento tienes acceso al arreglo de segmentos que estas indexando?

**Comment by fivaldivia** [comment]
Sí! Esta funcion recibe (Particle particle, Node *node), donde el nodo contiene un arreglo de segments.

**Comment by vichoeq** [comment]
Probaste que el nodo esté almacenando el arreglo correcto?

**Comment by fivaldivia** [comment]
Sobre eso, tengo una duda porque al inicializar ese arreglo no se cuanto espacio va a utilizar, por lo que lo inicializo como             ```Segment *segments = malloc(Numero_tamaño_original*sizeof(Segment));```. El numero tamaño original es como el máximo de espacio que podría ocupar, esto esta bien? O tal vez por eso me está tirando error?

**Comment by vichoeq** [comment]
Eso debería estar bien 🤔 luego pasas los elementos uno por uno?

**Comment by fivaldivia** [comment]
Sí! Le voy poniendo cada segmento por posición :/...

**Comment by vichoeq** [comment]
Qué dice valgrind cuando imprimes ese numero feo? tiene toda la pinta de ser memoria sin inicializar

**Comment by fivaldivia** [comment]
Mmm esque no se como hacer que me aparezca en valgrind, porque no me tira error, ya que alfinal nunca entra en la función "Si hubo intersección2: ``` if(sim->particles[p].intersected_segment)```, etonces no me sale nada.

**Comment by vichoeq** [comment]
Pero como hiciste para imprimir ese numero que me mostraste? Haz eso mismo pero con valgrind

**Comment by fivaldivia** [comment]
Puse un print nomas, pero ya me ayudaron!! Pude resolverlo gracias! El problema era que a mi función le estaba pasando una partícula, pero definiendo punteros se arregló!

**Comment by caespinoza5** [comment]
¿Pudiste resolver esto?

**Comment by fivaldivia** [comment]
Sii! Tal como dije, el problema se solucionaba creando un puntero hacia la partícula de mi main.c, para poder modificarle el valor en otra función!
