### ISSUE TITLE
Orden de los Segmentos

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2133-PUC/2020-2#80]
Hola, se puede asumir que el ID de los segmentos será igual a la posición dentro del array "segments". 

Ej:  i = segments[i].ID

Pregunto esto, porque se toma en cuenta solo la colisión con menor ID, entonces no sería necesario recorrer hasta la profundidad máxima y se detiene la búsqueda al encontrar la primera colisión.

**Comment by vichoeq** [comment]
Originalmente esto si es cierto, pero cuando calcules mediana va a cambiar el orden de los elementos de tu arreglo (asumiendo que usas el metodo visto en clases) asi que puede que se deje de cumplir.

**Comment by vichoeq** [comment]
Además, tu particula podria chocar con 2 segmentos que estén en hojas distintas. En ese caso el recorrer el arreglo en orden no te va a servir de mucho, ya que no sabes qué hoja vas a revisar primero.

**Comment by BenjaLepe** [comment]
Como lo puedo hacer en caso de que estén en dos hojas diferentes? Porque, por lo que entendí, la gracia de los arboles de búsqueda es que recorras solamente una rama del árbol hasta que llegues a una hoja, entonces no sería posible saber si la partícula chocó con otro segmento de otro nodo hoja.

No se si estoy muy perdido, pero eso era lo que yo entendí. Igual de todas formas, tienes razón con el tema de la mediana, ahí el orden del arreglo no importa para nada. Gracias!

**Comment by vichoeq** [comment]
Lo que pasa es que este no es un árbol de busqueda: es perfectamente posible que computes intersección con los segmentos de más de una hoja. Revisa el video de la sesión de ayuda, se habla de esto.
