### ISSUE TITLE
Tarea 1 - orden de vectores pi y pf de segmento

### ISSUE THREAD

**Issue by kmhaller** [IIC2133-PUC/2020-2#81]
Hola, se supone que el pi y el pf del segment están ordenados de alguna manera, como que el pi sea el que tiene el menor valor de x e y y el pf el mayor valor de x e y o pueden estar en cualquier orden?

**Comment by vichoeq** [comment]
Hola! Pueden estar absolutamente en cualquier orden. Y si no me crees, revisa los tests.
