### ISSUE TITLE
Código externo

### ISSUE THREAD

**Issue by agustin-rios** [IIC2133-PUC/2020-2#83]
Si creo un codigo de quicksort basado en uno que encontre en internet para ordenar partes de listas lo referencio en el informe?

**Comment by yerkko** [comment]
Hello, tienen que siempre referenciar su código. En alguna parte tiene que quedar de dónde lo sacaron, ojalá en el readme + comentario en código. No es que vayamos a leer su implementación en primera instancia, pero si el sistema de detección de plagio los marca, tendremos un antecedente de que no intentaron robar nada.
