### ISSUE TITLE
Tarea 1 - Análisis

### ISSUE THREAD

**Issue by topkaj** [IIC2133-PUC/2020-2#85]
Hola, 

Tengo dos preguntas:

1) En el apartado del análisis, el segundo punto pide analizar la _búsqueda_ en el árbol. ¿Se refiere a la búsqueda de un segmento particular, a alcanzar un nodo específico, o a otra cosa? 
Lo pregunto porque, si bien el resultado puede que no cambie mucho (i.e. la complejidad es la misma), la justificación puede variar y requerir mencionar cosas adicionales.

2) ¿Qué tan exhaustivos hay que ser en las justificaciones de las complejidades? Por ejemplo, ¿debo demostrar que la complejidad de buscar en un árbol binario balanceado es O(log n)? ¿o se puede considerar como visto en clases?

Gracias de antemano.

**Comment by vichoeq** [comment]
1. Se refiere a la consulta colisión particula x todos los segmentos (la cual busca en el árbol cuales son los segmentos con los que podría colisionar, para luego calcular la colision con un numero reducido de candidatos)

2. Puedes decir que eso se vio en clases.

**Comment by topkaj** [comment]
¡Gracias!
