### ISSUE TITLE
Tarea 1

### ISSUE THREAD

**Issue by fernandovegauc** [IIC2133-PUC/2020-2#87]
![Screenshot from 2020-09-12 10-34-36](https://user-images.githubusercontent.com/53880431/92996675-bfbfe800-f4e3-11ea-9570-7e28d32e1d80.png)

Hola! estoy teniendo un problema con la función particle_boundingbox_collision, en la imagen se ve claramente que la caja contiene a todas las particulas pero al llamar a la función con la caja creada me retorna 0. ¿que podría ser?
Gracias!

**Comment by yerkko** [comment]
Es necesariamente tu algoritmo, el código de colisión fue testeado en múltiples ocasiones. Por lo mismo, intentaría revisar los límites que defines así como si llamas bien a las funciones

**Comment by fernandovegauc** [comment]
Muchas gracias por reponder tan rápido, seguiré revisando mi código .

**Comment by fernandovegauc** [comment]
![image](https://user-images.githubusercontent.com/53880431/92997945-4f1dc900-f4ed-11ea-9d41-571feedb3581.png)
Me está pasando algo muy extraño, cuando lo tengo así no entra al if pero si le pongo sim->particles[30] si entra. El problema es que ese p es un for que llega hasta 120 entonces si pasa por el 30 y debería entrar.

**Comment by caespinoza5** [comment]
¿Cómo tienes declarado el `for`?

**Comment by fernandovegauc** [comment]
es el for que viene en el código base en main, que itera sobre todas las particulas de la simulación.

**Comment by caespinoza5** [comment]
Y te imprime el `30` cuando haces prints de todos los p que iteras?

**Comment by fernandovegauc** [comment]
si!

**Comment by caespinoza5** [comment]
Asegurate que al entrar no estés eliminando segmentos o cosas de ese estilo
