### ISSUE TITLE
Tarea 1 [Diferencias de output text]

### ISSUE THREAD

**Issue by fivaldivia** [IIC2133-PUC/2020-2#88]
Hola, mi código está funcionando bien, crea las cajas, se realizan las colisiones bien donde ninguna partícula sale de los segmentos en la visualización. Además hago un print de las colisiones y resultan ser las mismas. Sin embargo, al comparar el output.txt con el solution.txt hay un par de líneas que resultan diferentes y nose por qué. Alguna recomendación de cómo encontrar la razón de porque algunas lineas son distintas? Ya que, haciendo prints me sale todo igual entonces nose que está fallando....

**Comment by yerkko** [comment]
Factores a considerar:

* Estás haciendo bien el desempate por ID? 
* Segur@ que no se te "pierde" ningún segmento?
* Estás deteniendo bien la recursión? 
* Revisando bien la intersección con el árbol?

Como puedes ver, son varios factores a considerar que pueden estar fallando en algunos casos particulares 🤔

**Comment by fivaldivia** [comment]
Hola, revisando el código entregado al inicio (sin cambios), me pasa que en el test_05  hay partículas que se quedan pegadas en algunas esquinas, esto está bien? Creo que puede ser algo con el desempate pero tengo el código inicial así:
```
for (int s = 0; s < sim->segment_count; s++) 
      {
        // Si la particula choca con el segmento
        if (particle_segment_collision(sim->particles[p], sim->segments[s])) {
          // Si es que no ha chocado con nada, o si no desempatamos por ID
          if(!sim->particles[p].intersected_segment || sim->segments[s].ID < sim->particles[p].intersected_segment->ID)
          {
            sim->particles[p].intersected_segment = &sim->segments[s]; 
          }
        }
      }
```
Aqui esta la foto, con algunas particulas que se quedan pegadas:
![image](https://user-images.githubusercontent.com/42453679/93000907-93b35f80-f501-11ea-8294-b44da4c16057.png)

**Comment by yerkko** [comment]
Es completamente normal que se queden pegados en las esquinas. Los resultados de los tests consideran esto.

**Comment by fivaldivia** [comment]
Ahhh, ok, gracias! Pero entonces como que en ese código he buscado que se realicen desempates y no me aparee que se hagan desempates. Esto lo hago con prints, y en mi codigo tampoco aparecen desempates...Entonces nose como revisaría si se están haciendo desempates, porque creo que nunca hay...

**Comment by yerkko** [comment]
El segundo if del código que muestras se encarga de eso

**Comment by fivaldivia** [comment]
Sí ! Lo se pero si hago :
```
if(sim->particles[p].intersected_segment)
{ print("%i, %i", sim->segments[s].ID, sim->particles[p].intersected_segment->ID);}
```
Para ver si ocurre alguna vez un desempate, nunca me imprime nada, entonces asumo que nunca hay desempate...

**Comment by fivaldivia** [comment]
El error que me está tirando es cuando uso la función ```particle_segment_collision(particle, segment)```, me esta diciendo que choca con segmentos que no debería, pero por que razón podría pasar esto? Ya que segun yo esa funcion me debería decir que esta chocando con segmentos que efectivamente están chocando con la partícula.

**Comment by caespinoza5** [comment]
¡Hola! Eso puede pasar por que estás escogiendo un mal bounding box de la caja. Asegúrate de estar usando aquellos puntos que realmente sean extremos 🙂

**Comment by fivaldivia** [comment]
Efectivamente ese era mi problema! Los puntos extremos se estaban definiendo mal, Muchas gracias!
