### ISSUE TITLE
[Tarea 1]  uso de nextafter de math.h

### ISSUE THREAD

**Issue by StroveLight** [IIC2133-PUC/2020-2#89]
Puedo usar la funcion ```nextafter()``` de math.h para obtener el float siguiente de un float?

**Comment by yerkko** [comment]
Puedes usar cualquier función de las librerías que "vienen con C" (hay que añadirlas a la makefile, math ya la incluímos nosotros)

Asegúrate que (1) no haya que instalar nada extra (2) compile con make
