### ISSUE TITLE
duda sobre revision de cajas en cada frame

### ISSUE THREAD

**Issue by rjdelrio** [IIC2133-PUC/2020-2#91]
una pregunta que aun no me queda clara, cuando tenga todos los segmentos en una caja, entonces tendre que iterar por una lista de cajas viendo si la particula esta en mi caja mas pequeña? o tengo que asumir que las particulas siempre estaran en la caja mas grande y tengo que hacer la busqueda de la caja en que estoi recursivamente? o tengo que ver primero si la particula esta en la caja mas grande, suponiendo que esta podria no estar y luego revisar en que caja esta recursivamente?

**Comment by vichoeq** [comment]
Hola, revisaste el video de la sesión de ayuda? Quizas te sirva pa aclarar como se relacionan las cajas.
