### ISSUE TITLE
Tarea 1 : Diferencias Output

### ISSUE THREAD

**Issue by emena97** [IIC2133-PUC/2020-2#92]
Hola, mi programa funciona y se ve bien en la visualización, pero cuando reviso el output me da que hay diferencias con el de solución, y no logro identificar cuál es el error.

**Comment by vichoeq** [comment]
Hola, actualizaste a la ultima versión del código base?

**Comment by bgfeuereisen** [comment]
Pudiste arreglar el error? ando con el mismo problema que el tuyo y no logro encontrar en que podría estar fallando
