### ISSUE TITLE
Tarea 1 - visualización de segmentos.

### ISSUE THREAD

**Issue by maormeno** [IIC2133-PUC/2020-2#93]
Si por algún motivo se me estuvieran modificando los valores de los pi y pf de los segmentos, estos cambios se verían reflejados en la visualización cierto?

Hice la función que calcula la mediana de la componente "x" de entre los puntos medios de los segmentos, la hice como lo vimos en clase, con la funcion partition y todo eso....  y me retorna un valor (que al ojo podría estar bien, aunque ni idea de cómo comprobarlo).
Pero me pasa que al llamar esa función (la llamo antes de todos los for, justo después de que el archivo se lee), cuando pongo para visualizar la ventana en True, muchas partículas no tienen un movimiento correcto (cruzan los segmentos o chocan contra segmentos invisibles), lo que no pasa cuando no llamo a la función; entonces probablemente se me estén modificando los segmentos de alguna manera al sacar la mediana.... pero si ese fuera el caso no debería verse reflejado en la visualización????

**Comment by yerkko** [comment]
Los segmentos se dibujan sólo una vez con los atributos originales, así que no se vería reflejado. Esto es un método común en todo tipo de visualización de objetos estáticos.

**Comment by vichoeq** [comment]
Sacar la mediana no te debería modificar los segmentos en sí, solo el orden en el que están en el arreglo.

**Comment by vichoeq** [comment]
Si quieres comprobar que no se rompió nada, recomiendo volver a dibujar los segmentos en la ventana, idealmente con otro color. Para eso puedes usar `set_color` y `draw_segment` de visualizer :)

**Comment by maormeno** [comment]
Efectivamente se me están cambiando los segmentos, lo voy a revisar, muchas gracias!!!
