### ISSUE TITLE
Uso de qsort - Tarea 1

### ISSUE THREAD

**Issue by ceosorio** [IIC2133-PUC/2020-2#97]
Hola!

Leí en discord que podemos probar la construcción de nuestro árbol usando **qsort**, pero en ese caso tenemos prohibido dejarlo con qsort y tener que después implementar median? Por que la complejidad computacional no la veo muy distinta entre ambas, pero no se si en volá no se puede :(

**Comment by yerkko** [comment]
Hello, pueden usar las funciones que quieran, mientras se cumpla lo de #89 y se mantenga la complejidad esperada.

**Comment by vichoeq** [comment]
Totalmente factible dejar **qsort** en tu solución, yo al menos nunca dije que no se podía :c Mi recomendación era probar con eso y de ahi, si querían, buscar la mediana con el algoritmo visto en clases.
