### ISSUE TITLE
Tarea 1: ¿Puede más de una caja tener el mismo segmento?

### ISSUE THREAD

**Issue by bpardobravo** [IIC2133-PUC/2020-2#98]
Hola, tengo una duda de como funciona el algoritmo (si cometo cualquier error entremedio, se agradece un aviso)
En el siguiente caso la linea verde se tira en el centro del segmento 4 porque es la mediana:
![hola](https://user-images.githubusercontent.com/48322933/93010424-b4f86800-f562-11ea-9e0a-4e03aab65292.png)
Luego a la izquierda de la linea verde quedan los segmentos 1,2,4 (incluyo el 4 por convención mía), y hago la caja según estos 3 segmentos así:
![hola2](https://user-images.githubusercontent.com/48322933/93010470-5089d880-f563-11ea-9699-fde8ac54773d.png)
Mi duda concretamente es: La caja morada (el nodo en el código) ¿contiene al segmento 3? Si no lo contiene, estaría no considerando uno de los segmentos mas cercanos a la pelota para checkear rebotes, y si en efecto lo contiene, habrían 2 cajas que contienen al segmento 3, la morada y la café:
![hola3](https://user-images.githubusercontent.com/48322933/93011040-37842600-f569-11ea-9bd0-7f7c5bfcccc5.png)

Resumen: ¿el segmento 3 está en el nodo de la caja morada o café?

**Comment by yerkko** [comment]
El segmento está en el café. No veo por qué no estarías detectando la colisión si tu código identifica correctamente que estás chocando tanto con la caja café como con la morada.

**Comment by bpardobravo** [comment]
Mala mía, quería dibujar el caso borde donde la pelota por muy poco no está en la caja café: 
![hola3](https://user-images.githubusercontent.com/48322933/93012242-0dd0fc00-f575-11ea-9de8-fa80ea3c09fb.png)

**Comment by yerkko** [comment]
Aún mejor el caso. Dado que la propiedad de una bounding box es que cubren completamente todos los segmentos, si no estás chocando con la caja café, es imposible que estés chocando con los segmentos dentro de esta. Entiendo que puede ser un poco contraintuitivo, pero no estamos haciendo búsqueda de k vecinos más cercanos.

**Comment by bpardobravo** [comment]
A!! ya entendí. Gracias
