### ISSUE TITLE
Triple for Tarea 1

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2133-PUC/2020-2#99]
Puedo crear un triple for para anotar todos los puntos medios de los segmentos? Y luego un doble for con el binary search de menor complejidad? Pregunto porque el primero supera la complejidad pedida pero no veo otra forma de anotar los puntos medios.

**Comment by yerkko** [comment]
A qué te refieres con "Puedo crear un triple for para anotar todos los puntos medios de los segmentos?" ?

**Comment by vichoeq** [comment]
Puedes hacer todo lo que quieras mientras tu programa de el mismo output que el codigo base (correctitud) y demore menos de 10 segundos en total (eficiencia / complejidad)
